### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by dantuin** [pypa/warehouse#2726] opened 2018-01-04 09:16 UTC
I created an account with wrong username by mistake and have no way to change it or recreate account with right one since the email address is already bound to the wrong one.
There are no packages associated with the account and old testpypi.python.org where it was possible to remove accounts is down.

Alternatively - is there anyone I can contact to get this resolved manually? (delete account or change username). I didn't find any relevant support email.
Thanks

**Comment by ewdurbin** [comment] 2018-01-04 13:23
As an aside, thank you for pointing out that testpypi is down! It's DB was replaced by the provider and the hostname changed.

**Comment by di** [comment] 2018-01-04 15:45
@dantuin Thanks for the report! Closing this as a duplicate of #423, since the ability to delete an account in Warehouse just hasn't been completed yet.

Now that https://testpypi.python.org is back up you should be able to delete your account there until #423 is completed. Feel free to comment here if you have issues.

**Closed by di** 2018-01-04 15:45 UTC
