### ISSUE TITLE
Pypi upload fails with httplib.BadStatusLine: ''

### ISSUE THREAD

**Issue by paulbrodersen** [pypa/warehouse#2682] opened 2017-12-18 16:53 UTC
This is a copy of [an issue I opened on pypi-legacy](https://github.com/pypa/pypi-legacy/issues/753#event-1392356831) that I was asked to migrate here. 

I maintain a small package called `netgraph`. The github code repository can be found [here](https://github.com/paulbrodersen/netgraph).
 
I have successfully uploaded new versions of the package half a dozen times or so with the following command: 

```
python setup.py sdist upload
```

However, the latest upload fails with: 

```
running sdist
running egg_info
writing requirements to netgraph.egg-info/requires.txt
writing netgraph.egg-info/PKG-INFO
writing top-level names to netgraph.egg-info/top_level.txt
writing dependency_links to netgraph.egg-info/dependency_links.txt
reading manifest file 'netgraph.egg-info/SOURCES.txt'
writing manifest file 'netgraph.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating netgraph-2.0.7
creating netgraph-2.0.7/netgraph
creating netgraph-2.0.7/netgraph.egg-info
copying files to netgraph-2.0.7...
copying setup.cfg -> netgraph-2.0.7
copying setup.py -> netgraph-2.0.7
copying netgraph/__init__.py -> netgraph-2.0.7/netgraph
copying netgraph/_interactive_variants.py -> netgraph-2.0.7/netgraph
copying netgraph/_line_supercover.py -> netgraph-2.0.7/netgraph
copying netgraph/_main.py -> netgraph-2.0.7/netgraph
copying netgraph/gallery.py -> netgraph-2.0.7/netgraph
copying netgraph/test_grandalf.py -> netgraph-2.0.7/netgraph
copying netgraph.egg-info/PKG-INFO -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/SOURCES.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/dependency_links.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/requires.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/top_level.txt -> netgraph-2.0.7/netgraph.egg-info
Writing netgraph-2.0.7/setup.cfg
Creating tar archive
removing 'netgraph-2.0.7' (and everything under it)
running upload
Submitting dist/netgraph-2.0.7.tar.gz to https://upload.pypi.org/legacy/
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    install_requires=['numpy', 'scipy', 'matplotlib'],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/upload.py", line 60, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/lib/python2.7/distutils/command/upload.py", line 175, in upload_file
    result = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

I suspect that this is a bug as reverting to a previous version that was previously successfully uploaded (specifically version 2.0.6) and attempting to (re-)upload that now also fails with the same error.
 
The error message is not particularly informative, and I am at a bit of a loss how to debug this issue and would appreciate some guidance on how to proceed. 

Ubuntu 17.04; tested in clean virtualenvs with minimal requirements installed for netgraph (numpy, scipy, matplotlib and their dependencies), both under python 2.7.13 and python 3.5.3.

**Comment by paulbrodersen** [comment] 2017-12-19 10:27
Ok, this issue just got really weird. If I connect to my university VPN, everything works fine. 

```
running sdist
running egg_info
writing requirements to netgraph.egg-info/requires.txt
writing netgraph.egg-info/PKG-INFO
writing top-level names to netgraph.egg-info/top_level.txt
writing dependency_links to netgraph.egg-info/dependency_links.txt
reading manifest file 'netgraph.egg-info/SOURCES.txt'
writing manifest file 'netgraph.egg-info/SOURCES.txt'
running check
creating netgraph-2.0.7
creating netgraph-2.0.7/netgraph
creating netgraph-2.0.7/netgraph.egg-info
copying files to netgraph-2.0.7...
copying README.md -> netgraph-2.0.7
copying setup.cfg -> netgraph-2.0.7
copying setup.py -> netgraph-2.0.7
copying netgraph/__init__.py -> netgraph-2.0.7/netgraph
copying netgraph/_interactive_variants.py -> netgraph-2.0.7/netgraph
copying netgraph/_line_supercover.py -> netgraph-2.0.7/netgraph
copying netgraph/_main.py -> netgraph-2.0.7/netgraph
copying netgraph/gallery.py -> netgraph-2.0.7/netgraph
copying netgraph/test_grandalf.py -> netgraph-2.0.7/netgraph
copying netgraph.egg-info/PKG-INFO -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/SOURCES.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/dependency_links.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/requires.txt -> netgraph-2.0.7/netgraph.egg-info
copying netgraph.egg-info/top_level.txt -> netgraph-2.0.7/netgraph.egg-info
Writing netgraph-2.0.7/setup.cfg
Creating tar archive
removing 'netgraph-2.0.7' (and everything under it)
running upload
Submitting dist/netgraph-2.0.7.tar.gz to https://upload.pypi.org/legacy/
Server response (200): OK
```

**Comment by di** [comment] 2017-12-19 14:55
Thanks for the report @paulbrodersen.

Since it seems like the problem is with your network and not with Warehouse, I'm going to close this issue, but feel free to comment here if you have any additional details.

**Closed by di** 2017-12-19 14:55 UTC
