### ISSUE TITLE
Update strings from source in Weblate

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#7409] opened 2020-02-19 11:31 UTC
https://hosted.weblate.org/projects/pypa/warehouse/#alerts

Weblate needs to periodically get new translation strings from the source. There's an alert about it but it seems it could be automated somehow (https://docs.weblate.org/en/weblate-3.11/admin/continuous.html#push-changes).

@ewdurbin @di ^

**Comment by di** [comment] 2020-02-19 17:52
I'm not sure if I follow what needs to be done here. I don't see anything actionable with that first link.

My understanding is that weblate is set up to monitor the repo and rebases new translations on top of every new change, producing PRs like https://github.com/pypa/warehouse/pull/7285 which need to be occasionally merged.

**Comment by webknjaz** [comment] 2020-02-22 14:24
That works for strings produced by the translators. But if the source changes, Weblate only shows that alert which means that it the original English strings in Weblate are different from the current master HEAD.

**Comment by webknjaz** [comment] 2020-02-22 14:26
So #7285 is Weblate->GitHub but GitHub->Weblate is not automated.

**Comment by di** [comment] 2020-02-24 20:49
The "Pushing changes" link you included seems to be the _final_ step in the process listed at the top of that page:

> 6. Once the translators are finished, Weblate commits the changes to the local repository (see [Lazy commits](https://docs.weblate.org/en/weblate-3.11/admin/continuous.html#lazy-commit)) and pushes them back if it has permissions to do so (see [Pushing changes](https://docs.weblate.org/en/weblate-3.11/admin/continuous.html#push-changes)).

But I think IIUC the problem is actually with step 3:

> 3. Weblate pulls changes from the VCS repository, see [Updating repositories](https://docs.weblate.org/en/weblate-3.11/admin/continuous.html#update-vcs).

From there I found https://docs.weblate.org/en/weblate-3.11/admin/continuous.html#automatically-receiving-changes-from-github, which says:

> If you are using Hosted Weblate, the recommended approach is to install the [Weblate app](https://github.com/apps/weblate), that way you will get the correct setup without having to set much up. It can also be used for pushing changes back.

So I've added that app to the repo and we'll see what happens.

**Comment by webknjaz** [comment] 2020-02-25 18:26
There's still an alert present from 14 hours ago (after you added the app).

It looks like we also need to automate strings collection.

Weblate takes source strings from https://github.com/pypa/warehouse/blob/master/warehouse/locale/messages.pot. And we need to update this file with the new strings from the updated templates. I think that new strings won't appear in the UI unless they are present in the original `messages.pot`.

**Comment by di** [comment] 2020-02-25 19:48
I'm not sure how it's possible to 'automate' strings collection, since it requires making a commit in this repo to update `messages.pot`.

I think the best we can do is ensure that contributors have this file is up-to-date before anything is merged, so I created #7443 to do this, which also saves us from having to manually and occasionally update this file.

**Comment by webknjaz** [comment] 2020-02-26 14:07
@di that looks good. Would you be open to a contribution of a GitHub Actions workflow that runs only if any template files are updated (can be any path glob actually) and updates `messages.pot` if it needs updating? I think I could do this if I have time at some point.

**Comment by di** [comment] 2020-02-26 15:27
I'm not in favor of automated commits to master. I'd rather just keep everything in the PR that's making the changes in the first place.

**Comment by webknjaz** [comment] 2020-02-27 12:45
@di but there's no guarantee that the submitter generated it correctly. Maybe an automatic PR creator then?

**Comment by di** [comment] 2020-03-10 22:28
> @di but there's no guarantee that the submitter generated it correctly. Maybe an automatic PR creator then?

The guarantee is running the same check in CI and seeing if there's any difference.

Looks like overall, this is now working as expected and I'm happy with the workflow, so I'm going to close. Thanks for raising this.

**Closed by di** 2020-03-10 22:28 UTC
Labels: i18n, translation
