### ISSUE TITLE
Too little information on search results page

### ISSUE THREAD

**Issue by levkowetz** [pypa/warehouse#3107] opened 2018-03-01 08:08 UTC
Trying out the new style and layout on an iPad, there are room for 5 search results on a page, as opposed to 31 with the old interface.  On my desktop the ratio is 9 to 38.  Now, you may argue that I don't need to see 39 results.  But I argue that I **do** want to see more than 5 results.

There is too much wasted screen real estate in the new look.  Please try to consider usability as well as style.  Does showing the same package cube on each search result really contribute to either style or usability?  Does the individual framing of each result line?

**Comment by di** [comment] 2018-03-01 16:11
Hi @levkowetz, thanks for the report. We've had similar feedback from users about the overall design, so I'm going to mark this as a duplicate of https://github.com/pypa/warehouse/issues/1988.

**Closed by di** 2018-03-01 16:11 UTC
Labels: UX/UI, search

**Comment by levkowetz** [comment] 2018-03-01 18:14
Ack.  And thanks for explicitly calling it out on #1988.
