### ISSUE TITLE
Search does not work correctly

### ISSUE THREAD

**Issue by socketpair** [pypa/warehouse#8526] opened 2020-09-08 18:35 UTC
```
$ pip3 search uring
io-uring (0.0.1)               - This is a light-weight python wrapper around "io_uring" linux library.
pycopy-cpython-ure (0.2)       - Pycopy module ure ported to CPython
micropython-cpython-ure (0.1)  - MicroPython module ure ported to CPython

$ pip3 search liburing
liburing (2020.7.13)  - This is a Python + CFFI wrapper around Liburing C library, which is a helper to setup and tear-down io_uring
                        instances.

$ pip3 --version
pip 19.1.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

Why the first query did not find `liburing` ?!

See pypa/pip/issues/8855

**Comment by di** [comment] 2020-09-08 18:38
Duplicate of https://github.com/pypa/warehouse/issues/5506.

**Closed by di** 2020-09-08 18:38 UTC

**Comment by socketpair** [comment] 2020-09-08 18:40
No! `liburing` has whitespace after name. Does not it ?
