### ISSUE TITLE
Project Author vs Maintainer vs Publish Permissions

### ISSUE THREAD

**Issue by timofurrer** [pypa/warehouse#1373] opened 2016-07-05 17:30 UTC
What kind of *Maintainers* are the ones shown on the left on a project page?
Are these the ones who have *publish permissions* on PyPI?
Or is it the author in the `setup.py`? 

What about the maintainer from the `setup.py`? It is certainly not used for the project page right now, but wouldn't it make sense to show this person as well?

Just for the sake of completion: The legacy PyPI only shows the *maintainer* field from the `setup.py` as *Author* on a package's page.

**Comment by dstufft** [comment] 2016-07-05 17:33
The ones you see on the left on Warehouse (with icons) are the ones who have publish permissions. We don't currently expose the ``Author`` orr ``Maintainer`` fields from ``setup.py, but issue #1060 is about adding that information.

One note though, legacy PyPI *does* show the ``Maintainer`` field independently of the ``Author`` field, *HOWEVER*, distutils and setuptools will send the ``Maintainer`` as if it were the ``Author`` when uploading a package to PyPI.

**Comment by dstufft** [comment] 2016-07-05 17:34
Closing as a duplicate of #1060.

**Closed by dstufft** 2016-07-05 17:34 UTC
