### ISSUE TITLE
WebAuthn support problem with Edge 77 (2FA)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6146] opened 2019-07-04 06:09 UTC
**Describe the bug**
When using Microsoft Edge 77.0.197.1, it appears that webauthn is supported (the button is enabled, no error message is shown), but when the user clicks on the 'provision key' button, nothing happens.

**Expected behavior**
A popup should be launched by the browser to provision the key.
Alternatively, if there is no browser support, the button should be disabled, and an error message shown.

**To Reproduce**
- Log into PyPI with Microsoft Edge 77.0.197.1
- Go to the 'my account page'
- Notice:  The 'setup 2fa with security key' button is enabled, and no error is shown
- Go to the key provisioning page
- Notice: The 'provision key' button is enabled, and no error is shown

**My Platform**
Microsoft Edge 77.0.197.1

**Comment by webknjaz** [comment] 2019-07-28 23:21
This looks suspiciously similar to #6264...

**Comment by woodruffw** [comment] 2019-07-31 14:26
#6305 should at least partially address this -- I was able to confirm via Browserstack that Edge now presents a WebAuthn prompt, and also renders errors correctly (I couldn't test the actual auth due to a lack of USB passthrough).

**Comment by brainwane** [comment] 2019-08-07 16:06
@nlhkabu Is this still reproducible?

**Comment by fuzzygwalchmei** [comment] 2019-08-08 10:04
using edge chromium Microsoft Edge Dev Build 77.0.235.4 im no longer having the issue and all working as expected now

**Comment by brainwane** [comment] 2019-08-08 17:55
Thanks @fuzzygwalchmei! I am going to close this bug now as it seems nonreproducible. If people run into it again, please reopen it.

**Closed** 2019-08-09 00:46 UTC
Labels: bug :bug:, cross browser bug :bug:, raised in user testing
