### ISSUE TITLE
Lost 2FA

### ISSUE THREAD

**Issue by mark9064** [pypa/warehouse#6484] opened 2019-08-17 23:26 UTC

**Comment by mark9064** [comment] 2019-08-17 23:26
I've lost my 2FA device, and as stated in https://pypi.org/help/ there's no way to recover my pypi account. As there's no way to do so, can I request that my account is deleted. The account name is mark9064 and the email is verified (so I can be contacted there for verification).
I'm opening an issue here as that's the recommended action for a password reset and I see no other option for direct email contact.

Thanks, mark9064

**Comment by brainwane** [comment] 2019-08-18 01:30
@jamadden or @yeraydiazdiaz could you take a look?

**Comment by yeraydiazdiaz** [comment] 2019-08-18 14:20
Hi @mark9064, sorry to hear you're locked out of your PyPI account.

It looks like you are the sole owner of [two projects](https://pypi.org/user/mark9064/), which means we will have to transfer them to an intermediate account and reassign it to you once you've created your new account.

Unfortunately moderators do not have the ability to perform these operations. We will contact the administrators and get back to you soon.

**Comment by mark9064** [comment] 2019-08-18 14:41
Thanks for looking in to this issue, apologies for being a pain :slightly_frowning_face:

**Comment by ewdurbin** [comment] 2019-08-21 14:26
Hi @mark9064! Please email ernest@python.org from the email address associated with your PyPI account. I'll send instructions on how to verify ownership of your existing email address and projects. Once that is complete and we will disable 2FA on your account and issue a password reset.

**Comment by ewdurbin** [comment] 2019-08-21 14:41
Confirmed email address, control of both projects on GitHub. I've disabled 2FA and issued password reset for this user.

**Closed by ewdurbin** 2019-08-21 14:41 UTC
Labels: support

**Comment by marsggbo** [comment] 2020-02-18 11:23
@ewdurbin I also have this problem, and I've sent an email to ernest@python.org. Looking forward to your reply. Thanks!
