### ISSUE TITLE
Allow version replacement on PyPI test instance

### ISSUE THREAD

**Issue by ncoghlan** [pypa/warehouse#868] opened 2015-12-27 01:45 UTC
(Turning [this suggestion](https://github.com/pypa/packaging-problems/issues/75#issuecomment-167372938) into a warehouse RFE)

Banning silent replacement of versions from the main pypi.python.org site is the right thing to do from an end user perspective, but from a publisher perspective, it would be useful if testpypi.python.org allowed version replacement, as that would permit the following publication workflow:

1. Publish to testpypi.python.org
2. Check the published package is working correctly
3. If not, fix the packaging and return to step 1 (without having to bump the version number)
4. Once the package is working correctly, push to pypi.python.org (locking in the version number)

This would be similar to the devpi based workflow some publishers already use, but without the need to host your own index server for testing purposes.

**Comment by dstufft** [comment] 2015-12-27 01:50
Duplicate of #720

**Closed by dstufft** 2015-12-27 01:50 UTC
