### ISSUE TITLE
make it easier/more obvious to filter by Python version

### ISSUE THREAD

**Issue by ThomasWaldmann** [pypa/warehouse#3008] opened 2018-02-20 23:16 UTC
if you have a project that only works on python 3 (or 2), but not on both, you want to filter such packages when searching for new libraries or other related packages for your project. similar if you only support e.g. >= 3.5 and you search for packages that support same py versions.

i am aware that not all projects have set the required metadata, but maybe making actual use of that metadata would be a motivation for them to finally add it.

![screenshot from 2018-02-21 00-12-50](https://user-images.githubusercontent.com/356103/36454394-ffa19384-169b-11e8-84eb-44a813d6d907.png)

**Comment by di** [comment] 2018-02-20 23:25
@ThomasWaldmann I think (if I understand correctly) what you're looking for is classifiers like `Programming Language :: Python :: 3`, which do exist: https://pypi.org/search/?q=&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3

Or are you suggesting that it should be possible to filter on the [`Requires-Python`](https://packaging.python.org/specifications/core-metadata/#requires-python) field?

**Comment by ThomasWaldmann** [comment] 2018-02-20 23:35
Looks like I missed that this is between all the other programming languages in the "By Programming Language" selection.

So, yes, it is there, but guess the UX could be improved.

**Comment by di** [comment] 2018-02-20 23:47
Duplicate of #2442.

**Closed by di** 2018-02-20 23:47 UTC
Labels: design, search
