### ISSUE TITLE
New Package Not Showing In Search Results

### ISSUE THREAD

**Issue by xloem** [pypa/warehouse#11515] opened 2022-06-05 15:11 UTC
**Describe the bug**
I uploaded https://pypi.org/project/RandomX/ to wrap a library with active maintenance, and it does not show in search results for me. 
Instead, https://pypi.org/search/?q=randomx gives me only  this list of packages:
- pyqrandomx 0.3.1 May 6, 2021 QRL RandomX library
- pyrandx 0.0.6 Feb 23, 2020 Python RandomX hashing module

**Expected behavior** 
Given the package name is the same as the search term, I would expect it to show in search results, or for me to be informed somehow if I did not package it properly.

**To Reproduce**
https://pypi.org/search/?q=randomx

**My Platform**
n/a

**Additional context**
https://github.com/xloem/RandomX

**Comment by di** [comment] 2022-06-05 15:26
Closing this as a duplicate of https://github.com/pypa/warehouse/issues/10718.

**Closed by di** 2022-06-05 15:26 UTC
Labels: bug :bug:
