### ISSUE TITLE
Color Markdown code blocks

### ISSUE THREAD

**Issue by hugovk** [pypa/warehouse#3585] opened 2018-04-08 15:03 UTC
It's great PyPI now accepts Markdown for descriptions! Thank you!

It would be nice if it also coloured code blocks, like GitHub does, and like PyPI does for RST.

## PyPI RST

https://pypi.org/project/pytest/

![image](https://user-images.githubusercontent.com/1324225/38469003-b241dd80-3b56-11e8-9f8f-73ae3172c60b.png)

https://raw.githubusercontent.com/pytest-dev/pytest/master/README.rst

![image](https://user-images.githubusercontent.com/1324225/38469012-d8746c8e-3b56-11e8-99cb-885e5c95f87a.png)

## PyPI MD

https://pypi.org/project/pylast/

![image](https://user-images.githubusercontent.com/1324225/38469017-fbd33a7a-3b56-11e8-90bd-ff889aa133d4.png)

https://raw.githubusercontent.com/pylast/pylast/master/README.md

![image](https://user-images.githubusercontent.com/1324225/38469015-e78d9d08-3b56-11e8-8e26-a41b467f7998.png)

**Comment by di** [comment] 2018-04-08 15:09
Thanks for the report! This is a duplicate of https://github.com/pypa/readme_renderer/issues/75 (and will be fixed soon by https://github.com/pypa/readme_renderer/pull/82)

**Closed by di** 2018-04-08 15:09 UTC
