### ISSUE TITLE
Versionless package(s) on pypi.org

### ISSUE THREAD

**Issue by Wouterkoorn** [pypa/warehouse#11323] opened 2022-05-03 14:20 UTC
While parsing through some projects and their packages on the simple index, I encountered a package without version number: https://pypi.org/simple/101903751-topsis/.
Some interesting thing to note:
- On the pypi.org frontend it displays version 1.0.0: https://pypi.org/project/101903751-topsis/#history
- The contents of the .tar.gz contains one subfolder called `101903751-topsis-1.0.0`, wherein the rest of the package files reside 
- The package was uploaded recently (so it's likely not not a leftover from an old, and already fixed issue)

I've tried looking a bit further, to see if there were more project with version less packages, but I didn't want to parse the html of all 372954 projects :). It at least does not seem too common, but there could be more than one.

**Comment by di** [comment] 2022-05-03 14:30
Duplicate of https://github.com/pypa/warehouse/issues/7811.

**Closed by di** 2022-05-03 14:30 UTC
Labels: bug :bug:
