### ISSUE TITLE
installing older version of supervisor is not found

### ISSUE THREAD

**Issue by SajEng** [pypa/warehouse#5448] opened 2019-02-18 11:16 UTC
**Describe the bug**
pip install supervisor==2.1

Could not find a version that satisfies the requirement 2.1 (from versions: )
No matching distribution found for 2.1

**Comment by mnaberez** [comment] 2019-02-18 18:17
Duplicate of Supervisor/supervisor#1204.  This is not a bug in warehouse.

**Closed** 2019-02-18 18:18 UTC
