### ISSUE TITLE
Copy to clipboard inserts a leading space

### ISSUE THREAD

**Issue by tirkarthi** [pypa/warehouse#4188] opened 2018-06-16 05:39 UTC
**Describe the bug**

* Copy to clipboard button to copy the pip install command inserts a leading space

**Expected behavior**

* No leading whitespace while pasting

**To Reproduce**

* Go to a module page
* Click on `pip install foo` with the copy to clipboard button
* Paste it in command line
* See an extra space in front

**My Platform**

* Browser : Firefox nightly, MacOS

**Additional context**

Since adding space in front skips the command from being added to the history file it's little difficult to see if I have already installed the module using search since the item is not added. I don't know if this is an intentional behaviour.

**Comment by ewdurbin** [comment] 2018-06-17 12:58
This seems to be specific to Firefox. I was able to reproduce using the current Firefox mainline release, but unable to reproduce on Chrome or Safari (All MacOS).

**Comment by tirkarthi** [comment] 2018-06-17 13:13
Thanks, I can confirm it's a Firefox issue and works fine in Chrome (MacOS).

Thanks

**Comment by ewdurbin** [comment] 2018-06-18 15:10
should be resolved with #4190, I'm no longer able to reproduce in any browsers I have installed.

**Closed by ewdurbin** 2018-06-18 15:10 UTC

**Comment by tirkarthi** [comment] 2018-06-18 15:17
I too verified the same. Thanks much @ewdurbin .

Thanks
