### ISSUE TITLE
Contact maintainer?

### ISSUE THREAD

**Issue by garyemiller** [pypa/warehouse#6115] opened 2019-06-27 20:13 UTC
How do I contact the maintainer? pip is serving a really, really, old copy of gps.

**Comment by jamadden** [comment] 2019-06-27 21:03
If you mean the maintainers and adminstrators of warehouse, this is as good a place as any. 😄 

If the project you mention is https://pypi.org/project/gps/, I can't reproduce a problem with pip installing an old version. The current version is 3.9, and that's what I get.

It could be a caching issue on PyPI's CDN, I suppose, in which case some details about your network environment (those requested by https://github.com/pypa/warehouse/blob/master/.github/ISSUE_TEMPLATE/access-issues.md) could help locate the problem.

**Comment by garyemiller** [comment] 2019-06-27 21:24
@jamadden "The current version is 3.9, and that's what I get."

No, the current gpsd version is 3.18.1.  3.19 will ship in July.  3.9 is six years old and not compatible with any gpsd of the last 5 years.  This package is useless.

Feel free to install gpsd from your fave distro and see if that pip package works with it.

Note the upstream dev is noted as Eric Raymond.  Feel free to contact him for confirmation.

**Comment by brainwane** [comment] 2019-06-28 19:05
I see that @frostoov is [the PyPI user](https://pypi.org/user/frostoov/) who uploaded version 3.9. [The release history](https://pypi.org/project/gps/#history) says he uploaded it on July 3rd, 2018.

I suggest @frostoov upload [3.18.1 (released 2018-10-19)](https://gitlab.com/gpsd/gpsd/blob/master/NEWS#L17); if he doesn't respond to this GitHub mention, I see his email address is listed on his GitHub profile, so @garyemiller could contact him that way.

If he doesn't respond, then please comment here and say so; in that case the [process of claiming an unmaintained/abandoned project](https://pypi.org/help/#project-name-claim) needs to proceed and we'll tag and follow up on this issue accordingly.

Hope this helps.

**Comment by garyemiller** [comment] 2019-06-28 22:27
How do I contact @frostoov ? 

 I see no email or contact info for himm on his PyPi user page.

I see no @frostoov on github.

I'm lost here.  Seems to me his PyPi user page should have contract info?

**Comment by yeraydiazdiaz** [comment] 2019-06-29 11:31
PyPI does not disclose email addresses of users.

https://github.com/frostoov is working for me and shows an email address, is that not working for you?

**Comment by garyemiller** [comment] 2019-06-29 20:56
"PyPI does not disclose email addresses of users."

Nor did I ever ask for that.  I just want a contact method.  An html form would do.

"https://github.com/frostoov is working for me:

Thank you, I did not find that.  It should not be that hard to contact a package maintainer.

Email sent to him.  Fingers crossed.

**Comment by brainwane** [comment] 2019-07-02 21:01
When I mentioned @frostoov in my comments, in the GitHub web interface that turned into a hyperlink linking to https://github.com/frostoov . In the future, if someone uses the @ symbol to mention someone in a GitHub issue or comment, you can find their GitHub profile that way.

We have #933 and #5944 open to add ways to make it easier for users to contact package maintainers via PyPI.

I'm closing this issue since you've now found a contact method to ask the maintainer to publish a new release. If the maintainer doesn't respond and you'd like to request a transfer of ownership, please comment here, reopen the issue, and say so. In that case we'll start on a [PEP 541](https://www.python.org/dev/peps/pep-0541/#reachability)-compliant process and follow up on this issue accordingly.

Best wishes in handling your "GPSes and other navigation-related sensors"! :-)

**Closed by brainwane** 2019-07-02 21:01 UTC
Labels: support

**Comment by garyemiller** [comment] 2019-07-02 21:05
The issue still remains.  I can not contact @frostoov and he is "releasing" old and broken software that people think is part of the gpsd that does not work with the gpsd project and has no possible use.

reopen, or I create a new issue, until this get fixed.

**Comment by garyemiller** [comment] 2019-07-02 21:11
To reconfirm: I have sent emails to  frostoov@gmail.com and receeive NO response.

PEP 541 is not exactly clear.  Do I need to now wait six weeks for an answer before proceeding?  Seems to me that 6 years without an update should be clear indication of being unmaintained.

**Comment by garyemiller** [comment] 2019-07-02 21:13
How do I demonstrate, for the PEP, my contact attempts?  Who should I copy?

**Comment by yeraydiazdiaz** [comment] 2019-07-03 08:05
Hi @garyemiller. Please open a PEP 541 issue referring this one and we'll start the due process. This will start with us moderators attempting contact directly. Please understand this is a volunteer ran process so it might take some time.

We do follow the PEP closely so yes, a period of 6 weeks is required until the project is considered abandoned. Please refer to the PEP for more details on what to expect moving forwards.

Thanks for understanding.

**Comment by garyemiller** [comment] 2019-07-03 20:38
Strangely @frostoov has reached out to another member of the gpsd team about this.  Much confusion as he has no clue what is going on, and the assumption is that I was also copied, but I have not been.

So the mess continues, but now a mess in my playpen that I can likely sort out.  Thanks for the help, gpsd is now getting back on track.
