### ISSUE TITLE
How to deprecate a package at pypi.org?

### ISSUE THREAD

**Issue by guettli** [pypa/warehouse#8659] opened 2020-10-05 10:06 UTC
**What's the problem this feature will solve?**

If a package at pypi is deprecated, then it would be nice if an author could declare this in
an explicit way.

**Describe the solution you'd like**

Maybe a new attribute in the metadata dictionary would be a solution.

**Additional context**

Example: https://github.com/patarapolw/ankisync/issues/11

Ankisync is deprecated, and the author asks how to make a package deprecated.

**Comment by ewjoachim** [comment] 2020-10-05 10:32
Maybe the trove classifier `Development Status :: 7 - Inactive` ?

**Comment by ewdurbin** [comment] 2020-10-05 13:45
Closing as duplicate of #345

**Closed by ewdurbin** 2020-10-05 13:45 UTC
