### ISSUE TITLE
Warning on top is not centered

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#2844] opened 2018-01-26 13:39 UTC
<img width="1680" alt="screen shot 2018-01-26 at 7 06 55 pm" src="https://user-images.githubusercontent.com/3275593/35442138-26b85d92-02cc-11e8-9f6c-5ffbc8da8d16.png">

Zooming out seems to show it is sticking to the right edge.

/request-tag design

**Comment by nlhkabu** [comment] 2018-01-31 21:03
hi @pradyunsg can you please confirm which browser you are seeing this on?

I can't seem to reproduce on pypi.io:

![screenshot from 2018-01-31 21-02-22](https://user-images.githubusercontent.com/3323703/35647347-20e3db92-06ca-11e8-8882-c9ea8b2c41cc.png)

Thanks

**Comment by di** [comment] 2018-01-31 21:12
I also can't reproduce.

**Comment by nlhkabu** [comment] 2018-02-02 06:31
Cannot reproduce on:

- ie11, ie10, ie9
- edge 16
- FF 58
- Chrome 64
- Opera 50
- Safari 5.1

@pradyunsg I'm going to close this, please let me know if you're still having issues and if you are, please provide the OS and browser :) Thanks

**Closed by nlhkabu** 2018-02-02 06:31 UTC
Labels: design

**Comment by pradyunsg** [comment] 2018-02-02 06:54
Hey! I thought I'd responded but evidently hadn't.

I tried it again and it seems to be just fine now. I guess it got fixed along with the PyPI description on landing. :)

Sorry for not mentioning the browser and OS. I think it was Chrome 64 on MacOS.
