### ISSUE TITLE
French sidebar on English locale

### ISSUE THREAD

**Issue by ryanlovett** [pypa/warehouse#6871] opened 2019-10-17 23:24 UTC
**Describe the bug**
French is used in the left sidebar on pypi.org even though I've chosen the English locale.

**Expected behavior**
The left sidebar is in English.

**To Reproduce**
1. Click English at the bottom of a pypi page.
2. See the green header "Locale updated" at the top.
3. Observe the terms "Statistiques", "Liens du projet", "Mainteneurs", etc. in the left sidebar.

**My Platform**
macOS; Google Chrome and Firefox

**Additional context**
I'll survive with the French terms. :)

**Comment by di** [comment] 2019-10-17 23:26
Thanks for the report! This is a duplicate of https://github.com/pypa/warehouse/issues/6834.

**Closed by di** 2019-10-17 23:26 UTC

**Comment by ryanlovett** [comment] 2019-10-17 23:56
Oops, thanks.
