### ISSUE TITLE
[Feature] User rating with several categories

### ISSUE THREAD

**Issue by GeorgeFischhof** [pypa/warehouse#1972] opened 2017-05-10 12:43 UTC
Hi There,

It would be good to implement a user rating mechanism into warehouse. Like ones used in the webshops or software stores. It would make the choice easier.

The categories could be for example:
easy usage
appropriate for its goal
easy to understand
novice or advanced 
high level or low level library

BR,
George

**Comment by di** [comment] 2017-05-10 14:33
Closing as a dupe of #991.

**Closed by di** 2017-05-10 14:33 UTC
