### ISSUE TITLE
Deleted items still exist

### ISSUE THREAD

**Issue by lingtianshi** [pypa/warehouse#10029] opened 2021-09-10 10:38 UTC
today, I upload some project , when i trying delete them, They still can be search, and enter return 404.

**Comment by meowmeowmeowcat** [comment] 2021-09-10 14:16
@lingtianshi What's your project? Could you provide the name of it? Please be noted that the search index may take some time to be updated.

**Comment by ewjoachim** [comment] 2021-09-11 14:30
Hello @lingtianshi,

Please confirm that the problem is not occuring anymore, now that the index is up to date.

Also, if not, please submit more details, such as the project name.

Let's close this ticket tomorrow if we don't have the details, but you can reopen it anytime.

**Comment by yeraydiazdiaz** [comment] 2021-09-20 11:50
Closing due to lack of response.

**Closed by yeraydiazdiaz** 2021-09-20 11:50 UTC
Labels: bug :bug:
