### ISSUE TITLE
Latest version of package is not listed on pypi.org or installable through pip

### ISSUE THREAD

**Issue by zreichert** [pypa/warehouse#4417] opened 2018-07-30 17:20 UTC
**Description**
I have built a new version of my package and I have uploaded it to pypi.org through twine.  The new package does not list as the latest version. [https://pypi.org/project/pytest-rpc/]( https://pypi.org/project/pytest-rpc/) 

**Expected behavior**
I expect to see my new release listed as the latest on the page for pytest-rpc
I expect to be able to see my release in the Release History section of pytest-rpc's page on PyPI
I expect to be able to `pip install pytest-rpc==0.10.0` successfully

**To Reproduce**
Attempt `pip install pytest-rpc==0.10.0`
Notice that you can navigate to this package on pypi.org  [https://pypi.org/project/pytest-rpc/0.10.0/](https://pypi.org/project/pytest-rpc/0.10.0/)

**My Platform**
Package built on Mac (10.13.5)
Python (2.7.10)
Uploaded with twine (1.11.0)
Attempted install with pip (9.0.3) & (18.0)

**Comment by ewdurbin** [comment] 2018-07-30 17:23
Almost certainly due to #4183, will confirm.

**Comment by ewdurbin** [comment] 2018-07-30 18:48
Confirmed. Executing the purge successfully exposed the new release and no failures/exceptions were found in log regarding the purge that should have occurred. This is being considered a duplicate of #4183.

**Closed by ewdurbin** 2018-07-30 18:48 UTC

**Comment by zreichert** [comment] 2018-07-30 18:57
Thanks! @ewdurbin
