### ISSUE TITLE
Unrendered long_descriptions stored in CDN

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#2718] opened 2018-01-02 02:56 UTC
Raised out of #2717, referencing other events.

- Checked sentry and did not see any Exceptions which were related to the project url in question
- Tested project with `readme_renderer` locally with no errors
- Tested project with `readme_renderer` on `python3.6.1-alpine` image with no errors
- Purged CDN, ✨ correctly rendered readme appears ✨

I'm not sure where to begin other than to possibly logging renders that fail for some reason, our caches are deep enough that this may not be _that_ bad.

**Comment by di** [comment] 2018-01-02 15:23
This sounds like a duplicate of #2582.

The odd thing about this that I have noticed since is that the unrendered `long_description` is the correct `long_description` for the release, which means that it's likely not a caching issue as it couldn't have been in the cache to begin with. Purging the cache just causes it to build that view again.

Not sure if it was the same for this instance, but that would make me think that `readme_renderer` is failing (non-deterministically?!).

I think some logging would be a good first step, specifically figuring out if/why `readme_renderer` is actually failing.

**Comment by di** [comment] 2018-03-06 20:49
I haven't seen this/#2582 in a while.

**Comment by di** [comment] 2018-03-14 20:08
Going to close this as I haven't seen it in a while.

**Closed by di** 2018-03-14 20:08 UTC
Labels: bug :bug:
