### ISSUE TITLE
display date user created account in Account Details

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5778] opened 2019-05-02 17:39 UTC
**What's the problem this feature will solve?**
Sometimes we maintainers want users with very old accounts to test a new feature, because old accounts have weird properties (see #3632). But if users don't know how old their accounts are, they don't know whether they should make a special effort to test the thing.

**Describe the solution you'd like**
A logged-in user should be able to see "Account created on `date`" in the Account Details section of their Account Settings page.

**Additional context**
(This would help me with [testing 2FA right now](https://wiki.python.org/psf/WarehousePackageMaintainerTesting)).

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by di** [comment] 2019-05-03 00:41
I've added the [good first issues](https://github.com/pypa/warehouse/labels/good%20first%20issue) label to this issue.

**Comment by theb10n707** [comment] 2019-05-04 19:58
I will work on this from Pycon2019 Mentor Sprints :)

**Comment by seandalaiocht** [comment] 2019-05-04 20:07
I'm also at Pycon2019 working with theb10n707 on this issue.

**Comment by dstufft** [comment] 2019-05-04 20:14
I think this already exists? I think the problem is we just don’t have that data before Warehouse took over registration, so a lot of uses have a null date.

**Comment by di** [comment] 2019-05-04 20:22
The timestamp exists, but we don't surface it in the logged-in UI.

**Comment by theb10n707** [comment] 2019-05-04 20:52
Looks like it is already available in the public profile. I will add it to the account settings page as well.

**Comment by brainwane** [comment] 2019-05-07 21:34
@theb10n707 how is this going? Need any help?

**Comment by di** [comment] 2019-05-07 21:48
Fixed in #5786.

**Closed by di** 2019-05-07 21:48 UTC
Labels: HTML, feature request, good first issue, help needed
