### ISSUE TITLE
There's a broken hyperlink pointing to a BigQuery guide in every single PyPI package page

### ISSUE THREAD

**Issue by rodrigobercini** [pypa/warehouse#9374] opened 2021-04-11 23:27 UTC
**Describe the bug**

The hyperlink that should be pointing to a Guide on how to Analyze PyPI statistics on BigQuery is broken and leads to an error page.

**Expected behavior**

Users click on "our public dataset on Google BigQuery" link and are directed to an existing page.

**To Reproduce**

1) Access any package page
2) Click on " our public dataset on Google BigQuery" in the left panel
3) Notice the issue (page doesn't exist)

Example: https://pypi.org/project/Flask-SocketIO/
![image](https://user-images.githubusercontent.com/18664907/114325017-281b8a00-9b04-11eb-9f08-af1895f1d03f.png)
![image](https://user-images.githubusercontent.com/18664907/114325023-2c47a780-9b04-11eb-884a-5853525c4c47.png)

**My Platform**

N/A

**Additional context**

I don't know which one should be the right link.

**Comment by yeraydiazdiaz** [comment] 2021-04-12 07:21
Hi @rodrigobercini thanks for the report. I can reproduce this but it's not clear it's warehouse problem.

The URL in the link is https://packaging.python.org/guides/analyzing-pypi-package-downloads/ if you try navigating from https://packaging.python.org/guides/ the very last link for "Analyzing PyPI package downloads" which references https://packaging.python.org/guides/analyzing-pypi-package-downloads.html also produces the "Maze found" error. 

Interestingly if you add any query arg at all it will work https://packaging.python.org/guides/analyzing-pypi-package-downloads.html?foo=bar.

I wonder if it's a problem with Sphinx or ReadTheDocs configuration.

**Comment by di** [comment] 2021-04-12 14:35
Thanks for the report. Looks like this was https://github.com/pypa/packaging.python.org/issues/876 and was fixed by https://github.com/pypa/packaging.python.org/pull/877.

**Closed by di** 2021-04-12 14:35 UTC
