### ISSUE TITLE
Different project count between simple index and pypi.org

### ISSUE THREAD

**Issue by kimadeline** [pypa/warehouse#7324] opened 2020-01-31 17:49 UTC
Hello 👋 

I was fiddling around with the simple index and I had a question: Why is the project count on https://pypi.org (215,670 as of right now) different from the number of links listed on https://pypi.org/simple/ (215,508)?

Thank you!

**Comment by di** [comment] 2020-01-31 18:30
Looks like the cache for `/simple` wasn't getting purged, all the missing projects were created today. I manually purged it and the totals now agree (215,677).

**Comment by kimadeline** [comment] 2020-01-31 18:35
Thank you for the explanation!

**Comment by di** [comment] 2020-01-31 18:40
Reopening this b/c the problem is likely going to persist until we determine why purging was failing.

**Comment by ewdurbin** [comment] 2020-01-31 19:52
It doesn't appear that there's anything broken in our CDN purging.

`/simple/` serves with `Surrogate-Key: all-html legacy/api/simple/index.html`. Neither of these keys are purged by our automated purging, in effect the fallback is that `/simple/` is [cached for one day](https://github.com/pypa/warehouse/blob/9ce63378181627aff66bb8959e1d9bb7e0366d02/warehouse/legacy/api/simple.py#L31) and can fall out of sync with the current count of projects in that time.

The best behavior would be for that route to be purged only when new projects are created or projects are deleted. Possibly the worst behavior would be for us to purge on `all-projects` key, as that is currently purged on any change to any Project or Release, which occurs _often_.

**Comment by songsammy** [comment] 2020-02-11 22:57
here's mine:
**Describe the bug**
When I tried to install some python packages via pip , i received 
(from versions: )
**Expected behavior**
install the package 
**To Reproduce**
$ pip install lxml
or
$ pip3 install lxml
**My Platform**

Linux version 5.0.0-38-generic (buildd@lgw01-amd64-036) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

**Additional context**
however when i tried a day later, the issue went away.

**Comment by di** [comment] 2020-03-25 03:36
Closing as expected behavior!

**Closed by di** 2020-03-25 03:36 UTC
Labels: CDN/network
