### ISSUE TITLE
Filtering PyPI Results Gives Unexpected Result Set

### ISSUE THREAD

**Issue by WayneLambert** [pypa/warehouse#8621] opened 2020-09-29 14:18 UTC
If I perform the following actions on PyPI, then I would expect different behaviour. Nothing is _broken_ on PyPI per-se, however it doesn't return search results that I would expect.

**To Reproduce**

- Go to PyPI.org
- Search for `hypothesis`
- On the left-hand side, click the `Development Status` filter
- Select `Production/Stable` checkbox
- As of writing this issue, there are 44 results
- Select `Mature` as well
- It now shows no results

In my mind, this should be an `OR` search and it appears as though it might be implemented as an `AND` search. As such, I would expect 44 or more results to be shown.

I checked a search by using the operating system filter too and that does give an `AND` search and in that case, I believe that to be correct as someone would want to know that the package is suitable for say Mac and also Windows.

In the case of a development status though, I think people would want to know whether a package has one status or another status.

**Comment by di** [comment] 2020-09-29 14:58
Duplicate of https://github.com/pypa/warehouse/issues/5765.

**Closed by di** 2020-09-29 14:58 UTC
