### ISSUE TITLE
Missing possibility of uploading a dist version in unpublished mode

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#4056] opened 2018-05-21 12:34 UTC
**Describe the bug**

I'm not sure whether to file it as a feature request or a bug, because it depends on the point of view.
So the issue is that in open source world many people use CIs with a limited free capacity for building their wheels. It might be not an issue for universal wheels, but when platform-specific wheels come into play it becomes a problem when different wheels appear at PYPI with up to 8 hours interval.
In my specific case it's about aio-libs/aiohttp and aio-libs/multidict.

We auto-publish distributions on tagged commits. Depending on which CI gets to the deployment stage first, different wheels start appearing there, which confuses the users and some third-party tools/integrations, which notice that the new version is there, available on PYPI, but when they try to `pip install` it, the tooling cannot find anything matching.

While for manylinux1 you can spawn a single docker container and get all the wheels you need, OS X builders in Travis CI are so slow and have to be in separate jobs. Take into account Travis' job queuing and prioritization and you'll see how easy it may become to stretch appearing of 20+ wheels of certain version across 8 hours (or even more).

So on one side it's a "bug" (design issue), on the other side it might be a feature request as well.

**Expected behavior**

I suggest having a feature to be able to "prepare" version for publishing publicly. For example, if all upload processes will send dists to PYPI in "unpublished mode" (invisible to end-users on UI or API).
And after everything is there it should be possible to flip a flag to actually "publish" dist version with all the artifacts at once.

**To Reproduce**

* https://github.com/aio-libs/multidict/issues/182
* https://github.com/aio-libs/aiohttp/issues/2347

**My Platform**

Travis CI + AppVeyor publishing to PYPI.

**Additional context**

‒

**Comment by di** [comment] 2018-06-02 17:31
This is essentially a duplicate of https://github.com/pypa/warehouse/issues/726.

**Comment by webknjaz** [comment] 2018-06-02 17:39
Oh, I didn't realize that. Should I copy this use case over to that issue?

**Comment by di** [comment] 2018-06-02 17:48
I think that issue mostly captures what you're asking for here, but feel free to chime in if you think there's something else that hasn't been considered.

**Comment by nlhkabu** [comment] 2018-07-26 15:46
Hi @webknjaz thanks for opening this issue.  I'm going to close it in favour of #726 - if you have more to add please comment over there :)

**Closed by nlhkabu** 2018-07-26 15:46 UTC
