### ISSUE TITLE
Include pip3 version of command on package webpage

### ISSUE THREAD

**Issue by CPSuperstore** [pypa/warehouse#6897] opened 2019-10-23 17:15 UTC
Hi! I was wondering if on a package page in the PyPI website, (ex. [this one](https://pypi.org/project/mysqlclient/)), where you have the text `pip install package`, and the button to copy to clipboard.
![Capture](https://user-images.githubusercontent.com/26421365/67417517-f83a9880-f596-11e9-9468-4fc23944cfea.PNG)

Could you also include the `pip3` version as well?
`pip3 install package`

Thank you for your time, and let me know if you need additional information
- Christopher Palazzolo :)

**Comment by di** [comment] 2019-10-25 15:40
There is no program called `pip3` -- that's just a wrapper provided by certain vendors.

There is an open discussion about improving this command at https://github.com/pypa/warehouse/issues/1563, so I'm going to close this as a "loose" duplicate of that issue, but thanks for the request!

**Closed by di** 2019-10-25 15:40 UTC
