### ISSUE TITLE
classifier vs classifiers in the upload api

### ISSUE THREAD

**Issue by konstin** [pypa/warehouse#9085] opened 2021-02-13 10:52 UTC
**Describe the bug**

The upload api used by twine generally accepts fields from the core metadata specification. But while the core metadata describes a field called `Classifier`, warehouse ignores `classifier` and instead wants `classifiers`. It seems that PEP 301 has introduced this mismatch, and setuptools/twine have kept it since.

**Expected behavior**

Since I don't expect that the fields of the upload api can be changed at this point, it would be good if there was some documentation about where the upload differentiates from the core metadata specification.

**To Reproduce**

Try uploading a package with `classifier` in the POST form-data, find that it doesn't show up in the ui.

**My Platform**
n/a

**Additional context**

This was first reported in https://github.com/PyO3/maturin/issues/407

**Comment by di** [comment] 2021-03-11 18:54
Closing as a duplicate of https://github.com/pypa/warehouse/issues/3151.

**Closed by di** 2021-03-11 18:54 UTC
