### ISSUE TITLE
github markdown: image sizes

### ISSUE THREAD

**Issue by nschloe** [pypa/warehouse#3501] opened 2018-04-02 08:25 UTC
GitHub markdown (like any markdown I suppose) is an extension of HTML. This fallback is sometimes needed, e.g., when resizing or centering images. This
```html
<p align="center">
  <img src="https://nschloe.github.io/meshio/meshio_logo.png" width="20%">
</p>
```
renderes a centered, 20% wide image on GitHub (https://github.com/nschloe/meshio). On PyPi (https://pypi.org/project/meshio/), not so lucky.

**Comment by nlhkabu** [comment] 2018-04-02 15:56
Hi @nschloe thanks for this ticket.  Would you mind opening two separate tickets for these issues?  We'll be likely to address them in two separate PRs, so this will make things easier for us :)

**Comment by nschloe** [comment] 2018-04-02 16:04
Sure thing. https://github.com/pypa/warehouse/issues/3508

**Comment by di** [comment] 2018-04-02 16:09
Duplicate of https://github.com/pypa/readme_renderer/issues/44.

**Closed by di** 2018-04-02 16:09 UTC
