### ISSUE TITLE
Some badges in long project descriptions on PyPI return HTTP 404

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#7505] opened 2020-03-07 16:20 UTC
**Describe the bug**

$sbj. It looks like this happens to badges with emojis in URLs.
In my case, it's GitHub Actions CI/CD workflow emojis.

**Expected behavior**

Badge displayed.

**To Reproduce**

It's visible here: https://pypi.org/project/ansible-collections.python.dist.boo/.
The corresponding GitHub page: https://github.com/webknjaz/ansible-collection-python-dist-boo.

The build process embeds `README.rst` as-is. You can see that the badge is visible on GitHub but on PyPI the corresponding HTTP request visible in DevTools returns 404.

I have another project where GitHub badges work (https://pypi.org/project/octomachinery/) and the only difference I see is emojis in the URL.

I'd try to debug it myself but I haven't found where the code that is used to cache images lives.

**My Platform**

N/A

**Additional context**

N/A

**Comment by ewdurbin** [comment] 2020-03-07 16:32
Images are proxied via https://github.com/pypa/warehouse-camo, so the issue is likely in its handling of URLs.

**Comment by di** [comment] 2020-03-07 21:42
Yeah, it's because the emoji are not URL-encoded:

```
_http_client.js:139
      throw new ERR_UNESCAPED_CHARACTERS('Request path');
      ^

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:139:13)
    at request (https.js:305:10)
    at Object.get (https.js:309:15)
    at process_url (/Users/dustiningram/git/pypa/camo/server.js:139:25)
    at Server.<anonymous> (/Users/dustiningram/git/pypa/camo/server.js:322:18)
    at Server.emit (events.js:210:5)
    at parserOnIncoming (_http_server.js:742:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
```

Using `https://github.com/webknjaz/ansible-collection-python-dist-boo/workflows/Publish%20Python%20%F0%9F%90%8D%20distributions%20%F0%9F%93%A6%20to%20PyPI%20and%20TestPyPI/badge.svg` instead should work.

**Comment by di** [comment] 2020-03-24 20:38
Closing this as there's not really much we can do here, but thanks for the report.

**Closed by di** 2020-03-24 20:38 UTC
