### ISSUE TITLE
No search result on pypi

### ISSUE THREAD

**Issue by ununhexium** [pypa/warehouse#3964] opened 2018-05-14 09:36 UTC
https://pypi.org/search/?q=Django
Shows 0 result for Django
Same for requests, jira, anything i tried actually...

**Expected behavior**
Show me something or tell me what's going wrong.

**To Reproduce**
https://pypi.org/search/?q=Django

**My Platform**
Firefox
Pip
Note: the search is also broken for pip, locally.

**Comment by ewdurbin** [comment] 2018-05-14 09:43
We're still sporadically running into the issue described in #3746. This incident of the issue is however resolved.

I'm going to close this issue as a duplicate of #3746

**Closed by ewdurbin** 2018-05-14 09:43 UTC
