### ISSUE TITLE
Feature Request: Add emoji support for Readme

### ISSUE THREAD

**Issue by TheCodersHangout** [pypa/warehouse#4334] opened 2018-07-21 13:20 UTC
**What's the problem this feature will solve?**
Add emoji support for Readme

**Describe the solution you'd like**
It looks beautiful like in NPMJS

**Comment by di** [comment] 2018-07-21 14:06
Thanks for the request! This is a duplicate of https://github.com/pypa/warehouse/issues/1663.

**Closed by di** 2018-07-21 14:06 UTC
