### ISSUE TITLE
https://pypi.org/simple/  index seems to be behind by 8k+ updates

### ISSUE THREAD

**Issue by zsimic** [pypa/warehouse#9926] opened 2021-08-18 01:08 UTC
I published a new project recently, and it's not showing up on https://pypi.org/simple/ after 18+ hours.
Whereas it is available when referenced directly: https://pypi.org/project/portable-python/

**Expected behavior**

Project should show on https://pypi.org/simple/ in a reasonable amount of time? 
Not sure what a "good time" would be, but I was hoping for less than 12 hours.

**To Reproduce**

```
curl -I https://pypi.org/simple/
...
x-pypi-last-serial: 11197400
# no mention of project "portable-python" on https://pypi.org/simple/


curl -I https://pypi.org/simple/portable-python/
...
x-pypi-last-serial: 11205924
```

`x-pypi-last-serial` is 8500+ updated behind on main index page.

**Comment by di** [comment] 2021-08-18 15:29
Closing as a duplicate of #8385 and #7384.

**Closed by di** 2021-08-18 15:29 UTC
Labels: bug :bug:

**Comment by zsimic** [comment] 2021-08-19 00:02
All issues related to this seem to get closed without a resolution.

If it helps: my package eventually showed up, apparently it needs 24+ hours to show up.
Perhaps that's OK... I guess 24 hours isn't that bad.

Posting this update here in case other people run into this, and think their package is stuck: it seems that the main index is simply refreshed with a very long delay.

Note: the main index is typically the source of truth of internal pypi mirrors, so one has to wait those 24+ hours for one's package to show up on an internal mirror basically.

**Comment by di** [comment] 2021-08-19 01:13
What mirror are you using? Most mirrors use the [XML-RPC mirroring APIs](https://warehouse.pypa.io/api-reference/xml-rpc.html#mirroring-support) and thus don't suffer from this. The simple API and this endpoint is not intended to be a source of truth for mirrors.

**Comment by zsimic** [comment] 2021-08-19 03:44
We have a custom mirror (working on getting rid of it), which uses artifactory as backend...

If you have a recommended mirror, I'm all ears.

**Comment by di** [comment] 2021-08-19 10:30
See https://packaging.python.org/guides/index-mirrors-and-caches/

**Comment by zsimic** [comment] 2021-08-20 00:19
That page says "The XML-RPC API will be deprecated in the future".
Looking at the json API doc, it seems that it can't list all of the projects on pypi (which is needed if one wants to do a mirror that incorporates all of open source pypi, with additional internal packages).

So it seems that there is no better way than looking at https://pypi.org/simple/

bandersnatch seems to be a no-go on that end, devpi maybe (will try it out, but last I tried it a long time ago, it wasn't very stable)
