### ISSUE TITLE
Upload to test PyPI failing

### ISSUE THREAD

**Issue by jtemporal** [pypa/warehouse#2243] opened 2017-07-26 20:11 UTC
Hi! After correcting the .pypirc as instructed on [here](https://github.com/pypa/python-packaging-user-guide/issues/353) (thank you again for that), I tried to upload the package to TestPyPI and got an error as follows:
```
$ twine upload -r pypitest dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading serenata_toolbox-12.0.4-py3-none-any.whl
HTTPError: 403 Client Error: You are not allowed to upload to 'serenata-toolbox'. for url: https://test.pypi.org/legacy/
```
Same error occurs while running 
```
$ python setup.py sdist upload -r pypitest
```
Already checked for issues related to this subject and coudn't find any.

**Comment by di** [comment] 2017-08-25 16:57
Hi @jtemporal, per the error, you don't have permissions to upload that package. Is it possible you're using the wrong username? I noticed your usernames on `pypi.org` and `test.pypi.org` are different:

* https://pypi.org/user/jtemporal/
* https://test.pypi.org/user/jessicatemporal/

**Comment by di** [comment] 2017-08-25 17:53
I'm going to close this issue for now assuming that a username mismatch was the cause, but please feel free to comment here if that's not the case.

**Closed by di** 2017-08-25 17:53 UTC
