### ISSUE TITLE
Project tabs stop working after screen resize

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2052] opened 2017-05-28 20:30 UTC
To replicate:

- Open the screen at any desktop resolution
- Visit any project page
- Reduce the screen size until the layout changes and the side tabs stack on top of each other
- Click on the tabs

Notice that while the *content* changes (as it should), the correct tab is not highlighted.

This bug happens in the reverse order too: e.g. if you start on a small resolution and resize to desktop.

I believe the code we need to edit is here: `warehouse/static/js/warehouse/utils/project-tabs.js`

**Comment by joedougherty** [comment] 2017-06-02 06:45
I believe that this issue is being caused by two things:

1.) The `projectTabs` function accepts an argument `inMobileState`, but this variable is only computed on the initial page load. Any change to the window size will not alter the initial value of this variable.

2.) The `projectTabs` function defined in `warehouse/static/js/warehouse/utils/project-tabs.js` is only fired once (on `docReady` in `warehouse/static/js/warehouse/index.js`). This explains why the tab selected code only works in the context of the original window size. 

I believe this can be solved by moving the code that sets `inMobileState` from `index.js` to the function declaration itself. This way, `inMobileState` will be re-evaluated every time `projectTabs()` is called. Secondly, `projectTabs()` needs to be called on window resize.

I've created PR #2075 to help. Please let me know if there is anything more I can do.

**Comment by dstufft** [comment] 2017-06-02 11:25
Thanks for your excellent overview of what was causing this issue and the PR that fixed it!

Closing this since https://github.com/pypa/warehouse/pull/2075 is merged and solves the problem.

**Closed by dstufft** 2017-06-02 11:25 UTC
Labels: bug, help required, javascript

**Comment by nlhkabu** [comment] 2017-06-02 17:06
thanks @joedougherty :man_dancing:
