### ISSUE TITLE
PEP 541: Add maintainer to thrift (maintainer is unresponsive)

### ISSUE THREAD

**Issue by jeking3** [pypa/warehouse#5346] opened 2019-01-27 16:32 UTC
Greetings,

I am on the Apache Thrift PMC, and currently our PMC Chair is the only one listed as a maintainer of the thrift package on pypi.  Our chair has gone unresponsive for a while now, and we're trying to get more folks who are doing releases added to package managers.  In this case, pypi needs additional maintainers of thrift.  If you can add me to the list of maintainers, that will resolve the issue.  My pypi username is jeking3.  

On our side, we're tracking this at https://issues.apache.org/jira/browse/THRIFT-4687
For proof of Apache Thrift PMC membership, see: http://people.apache.org/phonebook.html?pmc=thrift

**Comment by jeking3** [comment] 2019-02-01 05:08
When can I expect a decision or action on this?

**Comment by jamadden** [comment] 2019-02-01 13:44
The Apache issue you point to was opened on 2018-12-27 and last updated on 2019-01-07. 

The [thrift project on PyPI](https://pypi.org/project/thrift/) was last updated by its maintainer `jfarrell` on 2018-01-11.

The only email address we have on record for that user is `@apache.org`. Presumably you've tried to initiate contact using that address? I've also pinged it.

I've pinged the Author email for the project as well.

I find a Github account with a username matching the PyPI maintainer username. It's most recent activity was on https://github.com/apache/thrift/pull/1611 (creating the Thrift 0.12.0 release, which is what the issue linked to in Apache's JIRA was about), where @jeking3 also participated. Both are "contributors" to the project. This was in October 2018. I've pinged that account.

The PEP defines an abandoned project as:

> owner not reachable (see Reachability above);

"reachability" is supposed to be tried for six weeks, at least three times. 

> no releases within the past twelve months; and

Previous release was just over 12 months ago.

> no activity from the owner on the project's home page (or no home page listed).

The home page is listed as http://thrift.apache.org but it ultimately does link to https://github.com/apache/thrift

**Comment by jeking3** [comment] 2019-02-01 14:58
I will update this ticket with the results from the Apache Board, the project asked the board for guidance on how to proceed.

**Comment by jeking3** [comment] 2019-02-07 14:20
The Apache Thrift PMC is voting on replacing the chair because he is non-responsive.  The other project he is chair for (Apache Aurora) is likely to do the same.  We're also going to ask the apache board to try to contact him with information on file to check on his health and well-being.

**Comment by jeking3** [comment] 2019-02-10 19:00
The Apache Thrift PMC team voted to elect a new project chair today.  This won't be reflected until the next board meeting in February.  I will update you then.

**Comment by ksmets** [comment] 2019-07-11 09:14
Any update regarding this issue?

**Comment by jeking3** [comment] 2019-07-11 11:47
I have asked the new PMC to post here and confirm the change of ownership request.

**Comment by Jens-G** [comment] 2019-07-13 12:06
Hi @ksmets, 

I can confirm what Jim wrote. We want to switch the maintainer, since jfarrell is no longer responsive and also no longer the PMC chair (because of that). 

Is there anything besides the link(s) below and/or above that you need from me or from the Thrift PMC?

* [board meeting minutes](https://whimsy.apache.org/board/minutes/Thrift.html)

Have fun,
JensG

**Comment by Jens-G** [comment] 2019-07-13 12:08
@jeking3, @ksmets: BTW, can we have two maintainers or is it limited to one person? 

That would make things easier [if one gets under the bus](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by jeking3** [comment] 2019-08-01 00:56
We are starting another release cycle.  Sure it should not take as long as it has to fix an ownership issue like this?

**Comment by yeraydiazdiaz** [comment] 2019-08-08 09:40
Apologies for the delay in tackling this issue but please remember this is a volunteer effort and there is long backlog of PEP 541 requests.

**Comment by yeraydiazdiaz** [comment] 2019-10-19 11:43
Thanks for your patience on resolving this issue. I will now contact an administrator to proceed to adding your PyPI username `jeking3` as an owner of the `thrift` package.

**Comment by ewdurbin** [comment] 2019-10-22 15:21
`jeking3` added as Owner.

**Closed by ewdurbin** 2019-10-22 15:21 UTC
Labels: PEP 541
