### ISSUE TITLE
requires-python = 3 refused by warehouse, not PyPI, valid according to pep 345

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#1446] opened 2016-08-28 17:43 UTC
Using `repository:https://upload.pypi.io/legacy/`

```
$ flit wheel  --upload
Copying package file(s) from test_requires_python_3_warehouse                                                                         I-flit.wheel
Writing metadata files                                                                                                                I-flit.wheel
Writing the record of files                                                                                                           I-flit.wheel
Wheel built: dist/test_requires_python_3_warehouse-0.0.2-py3-none-any.whl                                                             I-flit.wheel
Using repository at https://upload.pypi.io/legacy/                                                                                   I-flit.upload
Uploading dist/test_requires_python_3_warehouse-0.0.2-py3-none-any.whl...                                                            I-flit.upload
Starting new HTTPS connection (1): upload.pypi.io                                                       I-requests.packages.urllib3.connectionpool
Traceback (most recent call last):
  File "/Users/bussonniermatthias/.local/bin/flit", line 4, in <module>
    main()
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/__init__.py", line 88, in main
    repo=args.repository)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/wheel.py", line 191, in wheel_main
    do_upload(wheel_path, wb.metadata, repo)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/upload.py", line 164, in do_upload
    upload_wheel(file, metadata, repo)
  File "/Users/bussonniermatthias/.local/lib/python3.5/site-packages/flit/upload.py", line 133, in upload_wheel
    resp.raise_for_status()
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: requires_python: Invalid specifier in requirement. for url: https://upload.pypi.io/legacy/
```

Using classical PyPI endpoint

```
$ flit wheel  --upload
Copying package file(s) from test_requires_python_3_warehouse                                                                         I-flit.wheel
Writing metadata files                                                                                                                I-flit.wheel
Writing the record of files                                                                                                           I-flit.wheel
Wheel built: dist/test_requires_python_3_warehouse-0.0.2-py3-none-any.whl                                                             I-flit.wheel
Using repository at https://pypi.python.org/pypi                                                                                     I-flit.upload
Uploading dist/test_requires_python_3_warehouse-0.0.2-py3-none-any.whl...                                                            I-flit.upload
Starting new HTTPS connection (1): pypi.python.org                                                      I-requests.packages.urllib3.connectionpool
Package is at https://pypi.python.org/pypi/test_requires_python_3_warehouse
```

@takluyver pointed out to me that according to [pep 345](https://www.python.org/dev/peps/pep-0345/#version-specifiers) This shoudl be accepted:

> Requires-Python: 3 : Any Python 3 version, no matter which one, excluding post or pre-releases.

So  `3` seem to be a shorthand for `>=3,<4`; or the pep should be changed.

I've leaved the package on PyPI to do tests if requested but I should remember to delete it once this issue is closed. 

Thanks !

**Comment by Carreau** [comment] 2016-08-28 17:50
And  I _think_ I've tracked that to [`packaging:Specifier`](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L277-L370)

**Comment by dstufft** [comment] 2016-08-28 21:10
PEP 440 supersedes PEP 345 and it removes the idea of a "default" comparison operator, because there are too many different compatibility promises for a default and when we ditched the ``()`` in the dependency language there was no longer a way to do a default.

**Comment by takluyver** [comment] 2016-08-28 22:52
Fair enough, then we should check it in flit.

Is there (& should there be) a place to document specs separate from the
peps that establish them? Where multiple peps build on and modify one
another, it would be nice to have a single, up-to-date reference. For specs
in particular, peps are also written with less detail than I might like as
an implementor.

**Comment by dstufft** [comment] 2016-08-28 22:56
On pypa.io there is a page that attempts to do this, but I think he reality is that the older specs are not very fleshed out and their interaction with new specs are not super well defined always. 

As with a lot of things in packaging there is a lot that lives in the heads of the few (or sometimes just me) and we haven't done a great job at documenting it.

**Comment by Carreau** [comment] 2016-08-28 23:43
Just to be certain; is pep 345 completely superseded by 440, or does 440
only redefined the versioning scheme ?

In which case, should pep 345 be updated to match pep 440 ? Or should it be
marked as superseded by pep 440 ?

**Comment by dstufft** [comment] 2017-04-20 20:44
I'm going to close this, since this is working as intended.

**Closed by dstufft** 2017-04-20 20:44 UTC
