### ISSUE TITLE
Deletion/recreation of project does not reset version history

### ISSUE THREAD

**Issue by mixmastamyk** [pypa/warehouse#4644] opened 2018-08-29 16:45 UTC
**Background:** A user gave up an unused six-year old project and deleted it so I could use it.

I've created a new project with the same name, and uploaded a new version.

**Issue:**  I'm still restricted in that I can't create versions that already existed in the past, even after deleting the project and recreating it.

Am also having trouble with setup.py not working right so need to create lots of versions. :-/

Would like to wipe the entire slate clean and not be restricted by old versions.

**Comment by di** [comment] 2018-08-29 16:52
Hi @mixmastamyk, this behavior is by design. PyPI does not allow for the reuse of distribution filenames (project name + version number + distribution type).

This ensures that a given distribution for a given release for a given project will always resolve to the same file, and cannot be surreptitiously changed one day by the projects maintainer or a malicious party (it can only be removed).

Given that, I'm going to close this issue, but I'm happy to help with any `setup.py` issues you might be having here, feel free to comment.

**Closed by di** 2018-08-29 16:52 UTC

**Comment by di** [comment] 2018-08-29 16:54
Also, I should mention, you can use TestPyPI (https://test.pypi.org) to test publishing your package in an environment that doesn't affect the real PyPI, see https://packaging.python.org/guides/using-testpypi/.

**Comment by mixmastamyk** [comment] 2018-08-29 23:00
Hi,

I understand that's a thing.  But there's also the thing where cruft piles up over time.  If you don't allow cruft to be deleted, eventually everything will be cruft.

**Comment by mixmastamyk** [comment] 2018-08-29 23:06
My setup issue was trying to get "future fstrings" to not break the install, believe I've gotten past it now.
