### ISSUE TITLE
Package upload fails with internal server error (with twine and setuptools)

### ISSUE THREAD

**Issue by josine-cqm** [pypa/warehouse#7876] opened 2020-05-01 10:48 UTC
When I try to upload the attached package, I get an internal server error. Can anyone tell me what is wrong?
[packaging_tutorial.zip](https://github.com/pypa/warehouse/files/4563674/packaging_tutorial.zip)

**Comment by di** [comment] 2020-05-01 17:28
When I attempt to publish these distributions, this is the error I'm seeing:

```
HTTPError: 400 Client Error: Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE' is not a valid classifier. for url: http://localhost/legacy/
```

This classifier is not a valid classifier. Valid classifiers are listed at https://pypi.org/classifiers.

If I make this change, the upload succeeds:

```diff
-         "License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE",
+         "License :: OSI Approved :: GNU General Public License (GPL)",
```

**Comment by josine-cqm** [comment] 2020-05-03 11:14
> When I attempt to publish these distributions, this is the error I'm seeing:
> 
> ```
> HTTPError: 400 Client Error: Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE' is not a valid classifier. for url: http://localhost/legacy/
> ```
> 
> This classifier is not a valid classifier. Valid classifiers are listed at https://pypi.org/classifiers.
> 
> If I make this change, the upload succeeds:
> 
> ```diff
> -         "License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE",
> +         "License :: OSI Approved :: GNU General Public License (GPL)",
> ```

That is weird, I get a different error. It is the error below (I also get this error when I make the change you suggest):
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 5 of 5
Content received from server:
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>

HTTPError: 500 Server Error: Internal Server Error for url: https://test.pypi.org/legacy/

**Comment by di** [comment] 2020-05-04 19:50
Hi @josine-cqm, can you give us some more details? How are you authenticating? What user on pypi.org are you trying to upload with? What version of `twine` are you using?

**Comment by josine-cqm** [comment] 2020-05-05 08:05
Hi @di ,
Here are the details you asked for:
- I use testpypi for uploading: 
`python setup.py sdist bdist_wheel`
then
`python -m twine upload --repository testpypi dist/*`
My python version is 3.7.6
- I am authenticating with `__token__`  and `pypi-<password>`
(following the tutorial on [https://packaging.python.org/tutorials/packaging-projects/](url))
- my testpypi user is josine_cqm
- this is my twine version: 
![image](https://user-images.githubusercontent.com/64597748/81045559-b9c35600-8eb6-11ea-87ab-84598f9e77f6.png)

**Comment by di** [comment] 2020-05-05 15:42
Hi @josine-cqm, can you try to make an upload again and then tell me exactly what time you got this error? That way I can correlate this error to an exception in our backend.

**Comment by josine-cqm** [comment] 2020-05-06 07:30
Hi @di ,
I tried it just now again. At 9:29 Dutch time.

**Comment by di** [comment] 2020-05-06 07:51
Here's the corresponding exception: https://sentry.io/share/issue/8737571d268f41ae9eef2d12279882d2/

It looks like your API token is malformed. You said you're using `pypi-<password>`, is the string after `pypi-` your actual password, or an API token that was generated for this project on TestPyPI?

**Comment by di** [comment] 2020-05-06 07:52
It actually seems like the token being provided is `'pypi-'`, with just a single space instead of the token value.

**Comment by di** [comment] 2020-05-06 07:54
And looks like it's not in fact an empty space, but this character: https://www.utf8icons.com/character/65533/replacement-character

**Comment by josine-cqm** [comment] 2020-05-06 08:12
Thanks for your fast response. That means the actual problem is that the password was wrong (it turns out I did an incorrect copy-paste). How come I did not get an authentication error like I get when I enter a password pypi-0?
With a correct copy paste, I got a successful upload. So thank you!

**Comment by di** [comment] 2020-05-06 17:15
Great, ultimately this is a duplicate of #7434 then, so I'm going to close. Thanks for the report!

**Closed by di** 2020-05-06 17:15 UTC
Labels: bug :bug:
