### ISSUE TITLE
How to manage a "company account"?

### ISSUE THREAD

**Issue by venthur** [pypa/warehouse#8869] opened 2020-11-25 08:30 UTC
**What's the problem this feature will solve?**

Assume we have a company that want's to publish FOSS packages. The company needs some kind of account, but not all employees should share the static username/password. The company has a certain fluctuation of employees, e.g. new employes come and others go.

**Describe the solution you'd like**

As a manager of the company, I'd like to give subset of my employees the ability to upload packages on behalf of the company. Subsequently I need to be able to:
* add new employees
* remove employees that are not with the company anymore

**Additional context**

**Comment by hugovk** [comment] 2020-11-25 12:42
Duplicate of https://github.com/pypa/warehouse/issues/201?

**Comment by di** [comment] 2020-11-25 13:16
Duplicate of #201.

**Closed by di** 2020-11-25 13:16 UTC
