### ISSUE TITLE
404 when download package

### ISSUE THREAD

**Issue by Tonkonozhenko** [pypa/warehouse#3705] opened 2018-04-16 15:39 UTC
Hi,

I get 404 when try to download `regex-2018.02.21.tar.gz` from package https://pypi.org/project/regex/

**Comment by asottile** [comment] 2018-04-16 15:40
This appears related to #3704 

This is the specific error message I'm getting:

```
Could not install requirement pip from https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 because of HTTP error 404 Client Error: Not Found for url: https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl for URL https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*)
```

**Comment by ewdurbin** [comment] 2018-04-16 15:41
some 404s were cached during resolution of #3702, those have been cleared.

**Comment by asottile** [comment] 2018-04-16 15:42
@ewdurbin the cache does _not_ appear to be clear:

```
$ rm -rf venv ~/.cache/pip/ && virtualenv venv
New python executable in /tmp/venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/venv/bin/python - setuptools pip wheel:
  Collecting setuptools
/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting pip
/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-9.0.3-py2.py3-none-any.whl/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  HTTP error 404 while getting https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*)
  Could not install requirement pip from https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 because of error 404 Client Error: Not Found for url: https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl
Could not install requirement pip from https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 because of HTTP error 404 Client Error: Not Found for url: https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl for URL https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl#sha256=86a60a96d85e329962a9e6f6af612cbc11106293dbc83f119802b5bee9874cf3 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*)
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 953, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/venv/bin/python - setuptools pip wheel failed with error code 1
```

**Comment by klwilson227** [comment] 2018-04-16 16:00
Running get-pip.py 404 appeared and is now resolved with the python-pip. Now it fails with a 503 Backend is unhealthy... error when attempting to download the wheel archive. Curl is able to reproduce the problem with the download as well as the pypi UI. 

curl https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl

**Comment by ewdurbin** [comment] 2018-04-16 16:01
the files hosting service is currently in flux as we try to resolve the 404s issue :/

**Comment by ewdurbin** [comment] 2018-04-16 16:28
We've rolled out a stop gap while we work towards complete solution.

**Comment by jackton1** [comment] 2018-04-16 17:01
Temporary Fix 

```
curl https://bootstrap.pypa.io/get-pip.py | python3
```

**Comment by ewdurbin** [comment] 2018-04-16 17:05
We're now moved over to the intended state and monitoring to ensure things are still 👌.

Not seeing redirect loops, 404s, or 503s 😅

**Comment by ewdurbin** [comment] 2018-04-16 19:51
See https://status.python.org/incidents/1y1f44q6srh2 for an incident report on this fiasco.

**Closed by ewdurbin** 2018-04-16 19:51 UTC

**Comment by kddejong** [comment] 2018-04-16 19:55
Looks like there is still an issue with test.pypi.org as well.  I'm guessing that is being worked on as well.

**Comment by ewdurbin** [comment] 2018-04-16 20:00
@kddejong thanks for the heads up! we most certainly forgot to port the change to test.pypi.org!

**Comment by kddejong** [comment] 2018-04-16 20:04
working now @ewdurbin .  Thanks.  Thank you for all the hard work and congrats on completing the change today.

**Comment by sehargul-123** [comment] 2019-10-24 05:46
I have installed tensorflow==1.8.0, I have to run a file in order to star my training. but I am getting this error. ModuleNotFoundError: No module named 'tensorflow.compat' then i wrote this command "pip install tensorflow.compat" I got following error ERROR: Could not find a version that satisfies the requirement tensorflow.compat (from versions: none) ERROR: No matching distribution found for tensorflow.compat.
I then wrote "sudo pip install tensorflow.compat" 
I got the following error
The directory '/home/sehar/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sehar/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tensorflow.compat
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/tensorflow-compat/

**Comment by ewdurbin** [comment] 2019-10-28 15:21
@sehargul-123 `tensorflow.compat` is a module provided by the tensor flow package itself, not a separate package on PyPI. a quick check of the [source](https://github.com/tensorflow/tensorflow/tree/93bc2e2072e0daccbcff7a90d397b704a9e8f778/tensorflow/python) for the release shows that it did not exist at the 1.8.0 version you have installed.

You may want to file your report with the author of your training material.
