### ISSUE TITLE
Deleting an API token from the created API token page fails

### ISSUE THREAD

**Issue by yeraydiazdiaz** [pypa/warehouse#6818] opened 2019-10-12 12:08 UTC
**Describe the bug**
After creating an API token a confirmation page is shown with the token itself, some copy about how to use the token and also a button to delete the token.

Attempting to delete the token brings up the confirm modal and upon submitting the form the page refreshes to show the create API token form with errors reading "this field is required" on both fields. The API token still exists.

**Expected behavior**
Submitting the confirm modal on the delete API token redirects to the create API token page and flashes a confirmation.

**To Reproduce**
1. Log in and navigate to http://pypi.org/manage/account/token/
2. Create an API token
3. Without leaving the confirmation page click on the "Remove token" button
4. Enter your username in the modal form and click "Remove API token"

The resulting page's title is "Error processing form" and the create API token form will be displayed with the errors "Specify a token name" and "Specify the token scope"

**My Platform**
macOS Mojave, Firefox 70

**Comment by di** [comment] 2019-10-12 12:17
Maybe a duplicate of https://github.com/pypa/warehouse/issues/6816?

**Comment by yeraydiazdiaz** [comment] 2019-10-12 12:22
No, this happens when using the English locale as well, though I did notice it while testing https://github.com/pypa/warehouse/pull/6819 in portuguese.

**Comment by ewdurbin** [comment] 2019-10-12 12:52
Confirmed, able to reproduce.

**Closed** 2019-10-13 18:54 UTC
