### ISSUE TITLE
Wheel is placed in the previous release rather than the newly registered one

### ISSUE THREAD

**Issue by dr-leo** [pypa/warehouse#2675] opened 2017-12-14 11:47 UTC
When releasing pandaSDMX 0.8, the Wheel was erroneously uploaded to v0.7.0:

https://pypi.org/project/pandaSDMX/0.7.0/#files

The source distro is in the right place though. Trying to re-upload the Wheel yields an error msg as the file is already present.

Environment:

Win7x64, Py3.5 32bit, Wheel 29.0, twine 1.9.1.

**Comment by di** [comment] 2017-12-14 17:51
@dr-leo How was this wheel generated? It's a little strange, because it contains metadata for both `0.7.0` and `0.8` which likely confused `twine`

```
$ tar -xvvf pandaSDMX-0.8-py2.py3-none-any.whl
x pandasdmx/agencies.json
x pandasdmx/api.py
x pandasdmx/model.py
x pandasdmx/remote.py
x pandasdmx/__init__.py
x pandasdmx/reader/sdmxjson.py
x pandasdmx/reader/sdmxml.py
x pandasdmx/reader/__init__.py
x pandasdmx/utils/aadict.py
x pandasdmx/utils/anynamedtuple.py
x pandasdmx/utils/__init__.py
x pandasdmx/writer/data2pandas.py
x pandasdmx/writer/structure2pd.py
x pandasdmx/writer/__init__.py
x pandaSDMX-0.7.0.dist-info/DESCRIPTION.rst
x pandaSDMX-0.7.0.dist-info/metadata.json
x pandaSDMX-0.7.0.dist-info/top_level.txt
x pandaSDMX-0.7.0.dist-info/zip-safe
x pandaSDMX-0.8.dist-info/DESCRIPTION.rst
x pandaSDMX-0.8.dist-info/metadata.json
x pandaSDMX-0.8.dist-info/top_level.txt
x pandaSDMX-0.8.dist-info/zip-safe
x pandaSDMX-0.7.0.dist-info/WHEEL
x pandaSDMX-0.8.dist-info/WHEEL
x pandaSDMX-0.7.0.dist-info/METADATA
x pandaSDMX-0.8.dist-info/METADATA
x pandaSDMX-0.7.0.dist-info/RECORD
x pandaSDMX-0.8.dist-info/RECORD
```

**Comment by dr-leo** [comment] 2017-12-15 08:13
After bumping the version in setup.py to 0.8, I did the usual
>>> python Setup.py build sdist bdist_wheel

However, the build subdir contained previous builds. And there was an
egg.info as usual. The upload with twine did not yield any error:

>>> twine upload dist/*

The dist dir contained only the two mentioned files.

**Comment by di** [comment] 2017-12-15 21:51
@dr-leo Thanks for the additional details. I'd recommend opening this issue in two other places:

* https://github.com/pypa/wheel/issues/ (to determine how and why that wheel was built the way it was)
* https://github.com/pypa/twine/issues/ (to determine if there is a way that twine can guard against this happening)

In this case, twine told Warehouse that this wheel was for version 0.7.0, so that's where it was put, and as such this doesn't seem to be an issue within the scope of Warehouse, so I'll close this issue.

**Closed by di** 2017-12-15 21:51 UTC

**Comment by dr-leo** [comment] 2017-12-18 19:55
Thanks. Done.

**Comment by dr-leo** [comment] 2018-04-09 12:46
I firmly believe this issue should be re-opened because
1. Warehouse is the only Gatekeeper capable of preventing PyPI from being polluted by faulty wheels (with two sets of metadata) generated by Buggy Wheel tool and uploaded by twine versions that do not perform the integrity checks.
2. Even if twine and/or Wheel were fixed, old versions would still potentially pollute PyPI.

See the closed issue at https://github.com/pypa/twine/issues/284

The Wheel People have so far vainly tried to reproduce the error. I'll see if I can set up a repo on github making the Buggy build process reproducible.

It should be a matter of a few lines in Warehouse to check if a Wheel to be uploaded contains more than one distinfo items and reject it in the affirmative.


Leo

**Comment by di** [comment] 2018-04-09 13:44
I think this is going to be more than "a few lines" because Warehouse does not do any introspection of the distributions it receives, it depends on the introspection that Twine has done and has provided as metadata along with the upload.

I think reproducing the issue is the first step here, though. I am not aware of any other similar occurrences, so fixing any original bug should probably be enough to resolve this.

**Comment by dr-leo** [comment] 2018-04-14 16:50
I have set up a repo demonstrating the bug:

https://github.com/dr-leo/wheelbug

It contains the build and dist dirs as well as egg.info.

It has two commits: The first is a snapshot at v0.9. The wheel is
buggy as it also contains the distinfo for the previous v0.8.2. The
2nd commit captures the state after building v0.10. The new wheel
contains three distinfos, namely for 0.8.2, 0.9 and 0.10. It looks
like this appending business could continue forever.

Hope this helps to reproduce the bug or at least to add a sanity check
to warehouse.

That said, I would love to see the build toolchain fixed to avoid
building such insane wheels in the first place.

**Comment by dr-leo** [comment] 2018-05-07 09:56
I am afraid I am somewhat confused by multiple issues opened on the
same problem.

So I re-post my earlier messages in this thread.


Done. See the latest commit containing the newly created build and
dist dirs. - There is a single distinfo in dist.win32, as you can see.
So the wheel seems to be correct now.

I might add that the build process Ends with an "Access denied" error,
a known issue on Windows in other circumstances. I have no idea which
Operation fails if any. Maybe an attempt to remove some files in the
build dir which interfere with the next build...
