### ISSUE TITLE
Image does not display on PyPI

### ISSUE THREAD

**Issue by ProGamerGov** [pypa/warehouse#6772] opened 2019-10-06 18:58 UTC
The third image from the top on my PyPI project doesn't show up: https://pypi.org/project/neural-style/

Unlike the large image near the bottom, there are no errors associated with the image and it's within the 10MB size limit. 

Chrome doesn't display the third image from the top, and Firefox only displays a broken image icon. The image itself works perfectly fine on Github. 

The direct link to the warehouse image is: https://warehouse-camo.cmh1.psfhosted.org/a6a98243202fd4c495a0b17564b57af7923475ed/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f50726f47616d6572476f762f6e657572616c2d7374796c652d70742f6d61737465722f6578616d706c65732f6f7574707574732f7374617272795f7374616e666f72645f6269672e706e67

**Comment by ewdurbin** [comment] 2019-10-07 17:47
The [file](https://raw.githubusercontent.com/ProGamerGov/neural-style-pt/master/examples/outputs/starry_stanford_big.png) that PyPI's image service "camo" is trying to access is being served with the header `Content-Type: application/octet-stream`. The service only attempts to serve responses which are in the [accepted mime types](https://github.com/pypa/warehouse-camo/blob/master/mime-types.json), which is leading to the error.

It's not clear to me why the file is being served with that Content-Type, but it is certainly the issue.

Thanks to @di who implemented a new `Camo-Error-Message` header for 404 responses from https://warehouse-camo.cmh1.psfhosted.org to debug.

**Comment by di** [comment] 2019-10-07 17:53
Duplicate of https://github.com/pypa/warehouse/issues/5596.

**Closed by di** 2019-10-07 17:53 UTC
Labels: support
