### ISSUE TITLE
Featured projects grid can be unaligned

### ISSUE THREAD

**Issue by Ivoz** [pypa/warehouse#952] opened 2016-02-01 21:23 UTC
![chrome_2016-02-02_08-20-47](https://cloud.githubusercontent.com/assets/199266/12731673/1a829b90-c986-11e5-8baf-fbe59133011f.png)

When one project's short description takes up two lines, it dealigns the succeeding boxes

**Comment by di** [comment] 2016-02-01 21:36
Duplicate of #827.

**Closed** 2016-02-01 21:53 UTC
