### ISSUE TITLE
Search does not always show exact match at top

### ISSUE THREAD

**Issue by aphedges** [pypa/warehouse#10356] opened 2021-11-15 03:04 UTC
**Describe the bug**
The top result of search is not always an exact match.

**Expected behavior**
The top result of search (at least when sorting by "Relevance") should always be an exact match.

**To Reproduce**
I found multiple instances:

- <https://pypi.org/search/?q=Jinja2> returns `Jinja` first and `Jinja2` as second
- <https://pypi.org/search/?q=chardet> returns `chardet2` first and `chardet` second
- <https://pypi.org/search/?q=mypy> returns `mypy1989` first and `mypy` second
- <https://pypi.org/search/?q=pandas> returns `pandas2` first and `pandas` second

**My Platform**
N/a

**Additional context**
All examples that I've noticed differ only by numbers at the end. It is not always wrong (<https://pypi.org/search/?q=beautifulsoup4> and <https://pypi.org/search/?q=flake8> work as expected) or wrong in a consistent way (the one with the trailing number is not always first or always second).

I'm not 100% sure this is a bug, but from #1213, exact string matches being first does seem to be the expected behavior.

**Comment by di** [comment] 2021-11-15 12:02
Duplicate of #2877.

**Closed by di** 2021-11-15 12:02 UTC
Labels: bug :bug:

**Comment by aphedges** [comment] 2021-11-16 03:04
Sorry about that! I did not see the other issue when I searched the issues.
