### ISSUE TITLE
Admonitions are not rendered correctly in reStructuredText `long_description`

### ISSUE THREAD

**Issue by cjw296** [pypa/warehouse#8913] opened 2020-12-12 15:38 UTC
`warning`, `danger` and `notes` sections are currently rendered incorrectly where ReStructuredText is used in a project's `long_description`.

For example: https://pypi.org/project/xlrd/

This should be rendered similar to the orange box on https://xlrd.readthedocs.io/en/latest/, which is rendering the same source code.

This is important, as the current rendering makes it easy to miss warnings and danger sections.

**Comment by di** [comment] 2020-12-12 15:46
Duplicate of https://github.com/pypa/warehouse/issues/8300.

**Closed by di** 2020-12-12 15:46 UTC
