### ISSUE TITLE
Reporting issues with malicious PyPI packages

### ISSUE THREAD

**Issue by cefn** [pypa/warehouse#4131] opened 2018-06-05 23:19 UTC
Hi there, 

I struggled to find a link to report an issue with a PyPI project.

I independently investigated the files of the package linked below and found this package not to be apparently malicious, but it doesn't run (setup.py is incorrectly configured so running tkwriter immediately fails) and it points to a github repository which is not its own, indicating that it has thousands of stars of approval...

https://pypi.org/project/tkwriter/

However, I speculate that if I did find something malicious I wouldn't be able to find the proper way to report it. Nothing is mentioned about this (e.g. reporting people using PyPI maliciously) on https://pypi.org/help/#feedback . So the main issue I'm raising is making it more obvious how to report something which is defamatory, illegal, malware etc.

**Comment by di** [comment] 2018-07-04 14:59
Thanks for the report @cefn! I agree, that package just seems broken and not malicious. I would recommend reaching out to the maintainer about it instead.

RE: reporting packages, closing this as a duplicate of https://github.com/pypa/warehouse/issues/3896.

**Closed by di** 2018-07-04 14:59 UTC

**Comment by justinTM** [comment] 2022-01-18 17:02
It is not possible to report packages on PyPi at this time. Hopefully this bug will be fixed soon.

**Comment by di** [comment] 2023-03-02 16:53
For future readers: reports for malicious projects should follow our security guidelines: https://pypi.org/security/
