### ISSUE TITLE
“500: Internal server error” when uploading a package to PyPI 

### ISSUE THREAD

**Issue by M1ha-Shvn** [pypa/warehouse#8531] opened 2020-09-09 05:10 UTC
Hi.

**Describe the bug**
I get "500: Internal Server Error" trying to upload my library [django-pg-hll](https://github.com/M1ha-Shvn/django-pg-hll) version to both pypi and testpypi (5 retries). There were no problems with uploading previous releases but it was a long time ago.

**Expected behavior**
Uploaded package

**To Reproduce**
1. Clone [django-pg-hll](https://github.com/M1ha-Shvn/django-pg-hll) 
2. Build it using `python setup.py sdist` and `python setup.py bdist_wheel`
3. Try uploading with `twine upload dist/* --skip-existing --verbose --repository-url https://test.pypi.org/legacy/`

**My Platform**
1. Ubuntu 18.04.3 LTS
2. python 3.8.0
3. twine 3.2.0

**Comment by di** [comment] 2020-09-09 15:44
Can you attach the files you're attempting to upload here?

**Comment by M1ha-Shvn** [comment] 2020-09-09 18:13
[django-pg-hll-1.2.1.tar.gz](https://github.com/pypa/warehouse/files/5197174/django-pg-hll-1.2.1.tar.gz)

[django_pg_hll-1.2.1-py2.py3-none-any.whl.zip](https://github.com/pypa/warehouse/files/5197176/django_pg_hll-1.2.1-py2.py3-none-any.whl.zip)

P. s. I've added `.zip` extension to whl file in order to upload it here, just remove it.

**Comment by di** [comment] 2020-09-10 21:11
Are you uploading with a username/password? Can you confirm whether you're able to log into pypi.org with the username/password you're using?

**Comment by M1ha-Shvn** [comment] 2020-09-11 06:54
Thanks. Looks like my password has been compromised. I've changed password and now it's ok. Though, it's strange to get 500 error from twine in this case.

**Comment by di** [comment] 2020-09-11 12:35
Closing as a duplicate of https://github.com/pypa/warehouse/issues/8431.

**Closed by di** 2020-09-11 12:35 UTC
Labels: requires triaging
