### ISSUE TITLE
How to contact a maintainer

### ISSUE THREAD

**Issue by Cecron** [pypa/warehouse#8384] opened 2020-08-06 09:14 UTC
**What's the problem this feature will solve?**
I see a package written by me on PyPI and would like to reach out to the maintainer who uploaded it, how can I do that? Via the, correctly stated, author email I get user requests for updating the PyPI project page.

**Describe the solution you'd like**
As a logged in user with a verified email address, I'd like a way to send a message to another user (in my special case that other user is a maintainer) that has a verified email address but opted-out from showing it publicly.

**Additional context**
I've searched and it seems that the maintainer email is available through some API.
I've also looked through the FAQ section without finding a solution.

**Comment by pradyunsg** [comment] 2020-08-06 10:02
If the author has provided an email, that is available in the "Meta" section of the "Project Description" in the left sidebar.

See https://pypi.org/project/sampleproject/ for example.

**Comment by Cecron** [comment] 2020-08-06 10:30
> If the author has provided an email, that is available in the "Meta" section of the "Project Description" in the left sidebar.

Yes, but it is the Maintainer (which I assume is the owner of the PyPI project page) I would like to reach, the author mail in this case goes to me ;-)

**Comment by jamadden** [comment] 2020-08-06 11:21
Maintainers may also choose to post their email addresses. If:

- The maintainer has a verified email address; and
- The maintainer has opted-in to displaying an email address; and 
- You are logged in to PyPI 

Then, when you click the link to a user profile under the "Maintainers" header in the left sidebar, you will see an email address.

For example, the maintainer `The_Compiler` of [pytest](https://pypi.org/project/pytest/) displays an email address on [their profile](https://pypi.org/user/The_Compiler/).

**Comment by Cecron** [comment] 2020-08-06 12:50
@jamadden @pradyunsg Thank you both for your clear explanations with example links.
I have updated the original post to reflect the new things I have learnt.

In my specific case, there are broken links on the PyPI package page and support requests are landing in the author email box.

**Comment by di** [comment] 2020-10-13 17:53
Thanks for the feature request! Closing as a duplicate of https://github.com/pypa/warehouse/issues/933.

**Closed by di** 2020-10-13 17:53 UTC
Labels: feature request
