### ISSUE TITLE
RST long_description passing check does not get rendered on Warehouse (or legacy-pypi)

### ISSUE THREAD

**Issue by vphilippon** [pypa/warehouse#2600] opened 2017-11-21 19:27 UTC
Hello all,

I have a README.rst file used for the `long_description` which passes the "official check", yet still won't render on Warehouse (or legacy-pypi).

I think this *isn't* related to the cache purge issue, as the file was changed and the changes do appear on the page (we changed from .md to .rst to get some nice formatting).

Here's the README.rst:
https://raw.githubusercontent.com/jazzband/pip-tools/1.10.2rc1/README.rst

and here's the check I perform:
```
$ pip install readme_renderer
$ python setup.py check --restructuredtext --strict
```
Also, in a python interpreter, calling `readme_renderer.rst.render` works fine too.

But here's the result on Warehouse and legacy-pypi (no rendering):
https://pypi.org/project/pip-tools/1.10.2rc1/
https://pypi.python.org/pypi/pip-tools/1.10.2rc1/

I wasn't sure if this should be tracked in the `readme_renderer` repo, but technically `readme_renderer` is fine and renders things alright on his own.

Some possibly useful information on my setup:
OS: Windows 10 (or Ubuntu 14.04.5 LTS, with Travis-CI)
Python: 2.7
`pip freeze --all` on my local machine, in a clean virtualenv used to reproduce:
```
bleach==2.1.1
docutils==0.14
html5lib==1.0b10
pip==9.0.1
Pygments==2.2.0
readme-renderer==17.2
setuptools==28.8.0
six==1.11.0
webencodings==0.5.1
wheel==0.29.0
```

**Comment by di** [comment] 2017-11-21 20:49
Hey @vphilippon, thanks for the report.

I'm noticing that there's an extra bit at the top of the description on PyPI that isn't in your `README.rst`:

```
pip-tools keeps your pinned dependencies fresh.

Home-page: https://github.com/jazzband/pip-tools/
Author: Vincent Driessen
Author-email: me@nvie.com
License: BSD
Description: 
```

It seems like this is due to setting `description=__doc__` in your `setup.py`, specifically because `__doc__` has newlines in it, which breaks parsing the package's metadata. Setting this to something like `__doc__.strip()` (or making the docstring a single line) should fix the issue.

I'm surprised that setuptools is allowing you to do this, since the `description` kwarg a.k.a [`Summary`](https://packaging.python.org/specifications/core-metadata/#summary) metadata field is supposed to only be a single line. This may be a bug or regression, so I'd recommend opening an issue [on the setuptools issue tracker](https://github.com/pypa/setuptools/issues).

I'm going to close this since the fault seems to lie somewhere before the package makes it to Warehouse, but feel free to comment here if you additional information to the contrary.

**Closed** 2017-11-21 21:17 UTC

**Comment by vphilippon** [comment] 2017-11-21 21:38
Thank you very much, I will make the change and test it out.

> I'm surprised that setuptools is allowing you to do this, [...] This may be a bug or regression, so I'd recommend opening an issue on the setuptools issue tracker.

I'll admit I'm not sure I understand enough the impact of this for Warehouse/pypi. You mentioned this broke the metadata parsing, but I wouldn't be able to explain this properly.
