### ISSUE TITLE
Remove bold from markdown code sections

### ISSUE THREAD

**Issue by cprogrammer1994** [pypa/warehouse#3939] opened 2018-05-10 15:19 UTC
Hi!

I think bold looks bad in the rendered version of the long description.
It appears in the code section for imports and numbers.

Thanks!

**Describe the bug**

bold looks bad, especially for numbers

![image](https://user-images.githubusercontent.com/11232402/39877243-1cdee440-547e-11e8-9130-0a470d49ce52.png)

**Expected behavior**

- do not use bold at all

---

> ### Here is how github renders it:

## Sample usage

```py
>>> import moderngl
>>> ctx = moderngl.create_standalone_context()
>>> buf = ctx.buffer(b'Hello World!')  # allocated on the GPU
>>> buf.read()
b'Hello World!'
```

For complete examples please visit the [Examples](https://github.com/cprogrammer1994/ModernGL/tree/master/examples/#readme).

## Easy to use with Pillow and Numpy

```py
>>> img = Image.open('texture.jpg')
>>> ctx.texture(img.size, 3, img.tobytes())
<Texture: 1>
```

```py
>>> ctx.buffer(np.array([0.0, 0.0, 1.0, 1.0], dtype='f4'))
<Buffer: 1>
```

**Comment by nlhkabu** [comment] 2018-07-29 07:16
It might be worth doing #4400 before starting on this ticket.

**Comment by mixmastamyk** [comment] 2018-07-30 15:01
Hmm, I tend to prefer bold for keywords, though it does seem a excessive for numbers.

Believe part of the problem is because of the difference in weights between normal and bold of this fonts.  The bold is a bit *too* bold. 

If you are using a custom font with several weights available, one can be selected with a number in css: `font-weight: 600` for example.

**Comment by gforcada** [comment] 2019-05-13 21:01
Is there anything missing here after #4959 was merged? :thinking:

**Comment by di** [comment] 2019-05-13 21:07
Nope!

**Closed by di** 2019-05-13 21:07 UTC
Labels: UX/UI, good first issue
