### ISSUE TITLE
License lacks copyright and CoC clause

### ISSUE THREAD

**Issue by techtonik** [pypa/warehouse#1030] opened 2016-03-18 16:09 UTC
The website says that copyright belongs to Python Software Foundation, but LICENSE file doesn't name any copyright holders, so it is invalid.

Also, the terms of contributing to this open source project essentially requires to accept CoC terms, and thus it is another addition to the license.

**Comment by dstufft** [comment] 2016-03-18 21:04
A license does not require enumeration of copyright holders to be valid so the license here is completely valid. The License also does not need to contain everything that is required of a user to contribute (for instance, contributing also requires creating a GitHub account right now, but it doesn't state that either). If someone does not want to accept the CoC they are free to take the code still and use it as the license allows, which includes modifying it and distributing those modifications. Outside of that, we've stated that we'll not accept modifications back into Warehouse from people who don't adhere to the CoC.

That being said, the copyright notice on Warehouse is somewhat misleading. The *content* of PyPI (the packages etc) are not copyright the PSF, but are the individual owners of those packages. The *code* is not copyright the PSF, but myself, Nicole, and all of the other contributors (we don't do copyright assignment). I've asked someone to bring it up with the PSF board what we should say there explicitly given the nature of PyPI and will update it based on what they suggest.

**Comment by techtonik** [comment] 2016-03-19 08:00
> A license does not require enumeration of copyright holders to be valid so the license here is completely valid. 

Actually Apache 2 license does require listing copyright holder (which is Apache Foundation in original text) in NOTICE file - https://www.apache.org/dev/apply-license.html#new This is because rights are granted by copyright holder - the entity who will be defending license claims in court in case of a violation - either him directly or as a representative. 

> The License also does not need to contain everything that is required of a user to contribute 

Right. But you can then replace the license with CoC. It won't be certified open source grant of rights though, but I guess it will be more complete than just choosing anything.

> Outside of that, we've stated that we'll not accept modifications back into Warehouse from people who don't adhere to the CoC.

And that's why I think it not pure open source project anymore. Like "you can not submit code to it if you're ... (choose your own filters for humans)". It is close to "you can't sell it", but works in different direction.

> That being said, the copyright notice on Warehouse is somewhat misleading.

Yes, I would say it is 100% wrong. But if PSF funded the work, they may have ownership mentioned in your work contract. Actually, I don't think that PSF should own the code - it should help ecosystem grow, not control it. Maybe the reason is that there are no people in PSF anymore? Maybe that's the problem? I can't find them on https://www.python.org/psf/

**Comment by dstufft** [comment] 2016-03-19 12:44
> Actually Apache 2 license does require listing copyright holder (which is Apache Foundation in original text) in NOTICE file

No it doesn't. The Apache Software Foundation requires Apache Software Foundation projects to include that, but nothing in the text of the license requires it. That URL is specific to Apache projects, as evidenced by the very paragraph:

> This document aims to help Apache developers understand what they need to do to apply the Apache License, Version 2.0 (ALv2) to Apache software (including source code, documentation, and binary distributions). It is not intended to supplant or otherwise modify any of the terms within the license itself. This is just descriptive guidance and Apache policy is to be found elsewhere.

> But you can then replace the license with CoC.

No, the license has nothing to do with contributing to the main project and they never do. The License tells you the rights of the person receiving a copy of the work and what they're able to do.

> And that's why I think it not pure open source project anymore. Like "you can not submit code to it if you're ... (choose your own filters for humans)". It is close to "you can't sell it", but works in different direction.

You're entitled to your opinion. I'm done discussing the license and whether or not Warehouse is a "pure open source" project though and I'd ask you to refrain from it as well. The license is going to remain ALv2 and we're going to continue having a CoC. I'm fine with the restrictions this imposes.

> If PSF funded the work, they may have ownership mentioned in your work contract.

They PSF has not funded any of the work. I suspect the reason the statement exists on Warehouse is because it exists on legacy PyPI. I suggest the reason it exists on legacy PyPI is because the theme was copied from the old www.python.org site and that was just copied with it. I'll get it figured out for what it should be.

**Comment by Lukasa** [comment] 2016-03-19 13:09
> And that's why I think it not pure open source project anymore. Like "you can not submit code to it if you're ... (choose your own filters for humans)". It is close to "you can't sell it", but works in different direction.

That is not and has never been the definition of an open source project. No open source software license has ever said anything along the lines of "you have a right to submit patches to a specific repository of this source code".

Allow me to *specifically* enumerate the rights granted to you by the Apache Software License 2.0:

- You have a "perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license" to do any of the following with the software in source or object form:
    - reproduce
    - prepare derivative works
    - publicly display
    - publicly perform
    - sublicense
    - distribute
-  You have a "perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable [..] patent license" (this grant has some exceptions) to do the following with the software without violation of patents held by contributors:
    - make
    - have made
    - use
    - offer to sell
    - sell
    - import
    - otherwise transfer
- You may "reproduce and distribute copies" of the software or any derivative work in any medium you so chose provided that you:
    - give any other recipients of the software or derivative works a copy of the license in this repository,
    - cause any modified files to carry prominent notices stating that you changed the files,
    - retain, in the source form of any derivative works that you distribute, all copyright, patent, trademark, and attribution notices from the source form of this software, excluding those notices that do not pertain to any part of your derivative work,
    - do some complex stuff with any NOTICE file that I'm not going to reproduce here
- You may add your own copyright statement to any modifications you make in your derivative work.
- You may add additional licensing terms in your derivative work (provided your use of this software complies with all of these license terms)
- If you choose to contribute, unless you state otherwise this license applies to your contribution.

Here are some things this license *explicitly* does not grant you:

- permission to use the trade names, trademarks, service marks, or product names of the copyright holders, except as required for reasonable and customary use in describing the origin of the software
- a warranty of any kind
- the right to hold a contributor liable for any damage you incur arising from the use **or inability to use** of the software

But here's the thing about copyright law: that statement of rights you have is *complete*. You don't have any other rights over this software except if the copyright holders grant you those rights. In particular, nowhere in this or any other open source license is any notion of a "right to contribute". All copyright holders retain the rights to refuse any contribution they like on any grounds they choose that are not outright illegal in the applicable legal jurisdictions.

Open source software has *never* required that people accept changes from anyone who proposes them. It's a weird misinterpretation to say otherwise.

**Comment by techtonik** [comment] 2016-03-20 09:09
> Allow me to specifically enumerate the rights granted to you by the Apache Software License 2.0:

Please tell me how the granting mechanism works without copyright statement, which is required by copyright law which covers the usage of licenses.

> permission to use the trade names, trademarks, service marks, or product names of the copyright holders, except as required for reasonable and customary use in describing the origin of the software

So I can't use name `warehouse` in general case? =)

> Open source software has never required that people accept changes from anyone who proposes them. It's a weird misinterpretation to say otherwise.

But it never required patents as well, and once they need appeared, it was included in (the Apache 2.0) license. Also, a copyright assignment appeared when it became clear that it is impossible to defend those license rights in court. So CLA was introduced now a CoC, but all those things are just project regulations that still come together.

**Comment by Lukasa** [comment] 2016-03-20 10:17
> Please tell me how the granting mechanism works without copyright statement, which is required by copyright law which covers the usage of licenses.

Because that is *not* required by copyright law, at least in the United States which is the relevant jurisdiction in this instance. It is well established legal fact that there is no requirement to provide a copyright notice on a work in the United States, and a basic Wikipedia search would have made this clear to you.

The *purpose* of providing a copyright notice is twofold: firstly, it allows people who would like to negotiate for other licensing terms an idea of who holds the copyright, and secondly it undermines the ability of an infringing party to claim that they were not aware that the work in question was under copyright. The first part is useful but not necessary, and the second part would be a pretty hard argument to swing in court because the "this is licensed under the Apache license" block appears all over the place in the source code.

> So I can't use name `warehouse` in general case?

That is entirely up to the copyright holders and any relevant trademark owners. In this case, as far as I am aware, there is no trademark in place, so you can use the name however you see fit. All the license says is that *just because* you have the source code, does not mean you can brand yourself the way the upstream project does. This clause is commonly used in software like Mozilla Firefox, which is why non-Mozilla builds of Firefox have to be called something else (e.g. Iceweasel).

> But it never required patents as well, and once they need appeared, it was included in (the Apache 2.0) license. Also, a copyright assignment appeared when it became clear that it is impossible to defend those license rights in court. So CLA was introduced now a CoC, but all those things are just project regulations that still come together.

These things are *nothing* alike. The patent grant is required because if someone contributes code that they hold a patent on, then the rights granted by the license cannot actually be used: while the license grants you the right to use the code as you see fit, the patents restrict your ability to use the software. This is a condition Apache 2.0 wants to protect against: situations where code is *technically* licensed under an open source software license, but is actually encumbered by patents such that the code itself cannot be used.

Secondly, as far as I'm aware this project does not require a CLA, so let's take that out of the discussion.

Third, the CoC does not in any way restrict someone's ability to use the rights granted by the license. You are not being compelled to abide by the CoC in order to use, distribute, modify, or anything else. The only thing the CoC covers is *contributing* to the project, which, as I discussed before, the license *does not grant you a right to do*.

**Comment by techtonik** [comment] 2016-03-20 11:57
> Because that is not required by copyright law, at least in the United States which is the relevant jurisdiction in this instance.

Wikipedia is not authoritative source, so is there a section in http://copyright.gov/title17/ that says that copyright statement is not required for software licensing to work? Because Apache 2.0 rules say that you MUST include NOTICE file WITH copyright statement and if authors of the license do this themselves, then I tend to stick to that practice unless there is a solid proof that it is optional.

>> So I can't use name warehouse in general case?
> That is entirely up to the copyright holders and any relevant trademark owners. In this case, as far as I am aware, there is no trademark in place, so you can use the name however you see fit.

Yes, but the text of license mentions `product names` along with trademarks.

> These things are nothing alike. The patent grant is required because if someone contributes code that they hold a patent on, then the rights granted by the license cannot actually be used: while the license grants you the right to use the code as you see fit, the patents restrict your ability to use the software.

Right, so if somebody approves code from somebody who did not abide by the CoC then nothing will happen, so CoC doesn't work if it is not enforced by patent or copyright or sjw law.

**Comment by Lukasa** [comment] 2016-03-20 12:12
> Wikipedia is not authoritative source, so is there a section in http://copyright.gov/title17/ that says that copyright statement is not required for software licensing to work?

[From the United States Copyright Office guidance on the topic](http://www.copyright.gov/circs/circ03.pdf):

> U.S. law no longer requires the use of a copyright notice, although placing it on your work is often beneficial.

That's about as clear as you can get.

> Yes, but the text of license mentions `product names` along with trademarks.

Yes, but again, note that the text of the license here is saying that the license does not automatically grant the right to use the term, *not* that the right cannot be granted by some other means. The license is simply clarifying that *it* does not provide that right, not that the right cannot be provided.

> Right, so if somebody approves code from somebody who did not abide by the CoC then nothing will happen, so CoC doesn't work if it is not enforced by patent or copyright or sjw law.

Leaving aside the sheer absurdity of the phrase "sjw law" for a moment...

Not all agreements need to be enforced by law! The idea that a code of conduct needs to have the weight of law is ridiculous.

A code of conduct is a voluntarily accepted constraint on behaviour. By adopting it, the project *chooses* to apply additional restrictions to contribution and behaviour in the context of the project. Those restrictions are not enforced by law, but by the maintainers themselves.

Yes, if the maintainers choose not to enforce the Code of Conduct, that does make it meaningless, but guess what: that's fine. The Code of Conduct is a social convention: a socially enforced standard of behaviour. The law is not involved here. For this reason, violating the code of conduct does not restrict your rights to do with the code what you will, which is *a good thing*: that's how open source works. All it does is govern your behaviour in *this space*, which will be enforced by the maintainers of *this space*.

This is not a complicated idea.

**Comment by techtonik** [comment] 2016-03-20 12:50
>> Wikipedia is not authoritative source, so is there a section in http://copyright.gov/title17/ that says that copyright statement is not required for software licensing to work?

> From the United States Copyright Office guidance on the topic:

That's a good one. Thanks.

>> Yes, but the text of license mentions product names along with trademarks.

> Yes, but again, note that the text of the license here is saying that the license does not automatically grant the right to use the term, not that the right cannot be granted by some other means. The license is simply clarifying that it does not provide that right, not that the right cannot be provided.

I thought it is additional restriction placed by licence. Because otherwise it means that you can not use product names by default.

> Leaving aside the sheer absurdity of the phrase "sjw law" for a moment...

JFYI, "sjw law" means that if you not obey, they will troll you to the death like they've done with Gratipay.

> Not all agreements need to be enforced by law! The idea that a code of conduct needs to have the weight of law is ridiculous.

The idea of CoC is doubtful in itself - it looks like just another rule for banning somebody or placing them into ignore list. I would be just happy if Gratipay could just outsouce dealing with clashes between views of its users to government which is supposed to take care of that "diversity" stuff.

**Comment by Lukasa** [comment] 2016-03-20 13:48
> I thought it is additional restriction placed by licence. Because otherwise it means that you can not use product names by default.

No, the license is simply saying that it does not grant that right, not that it forbids it being granted in any other way.

> The idea of CoC is doubtful in itself - it looks like just another rule for banning somebody or placing them into ignore list.

That is exactly what a Code of Conduct is for. What I'm trying to explain is that that has nothing to do with software licensing. Software licensing is a matter of copyright law. They have to be read like legal documents because copyright is a legal construct.

Codes of conduct are a matter of social behaviour and convention: they are an expression of what kinds of contributor behaviour are accepted and what kinds are not, and the repercussions for failing to adhere to that behaviour.

All social interactions are governed by codes of conduct: most of the time they're just implicit. The same way there's lots of behaviour you wouldn't tolerate from guests at your house, there is behaviour that is not tolerated in online communities. The only change from having a code of conduct is that those behaviours are enumerated ahead of time, so that no-one can claim that they "didn't know" their behaviour was going to get them in trouble.

But remember: a code of conduct, unlike a software license, is not a legal document. Violating it is not cause for legal action. You can't go to prison for violating a code of conduct. You can only be subject to social punishments, which you're already subject to in the world.

> I would be just happy if Gratipay could just outsouce dealing with clashes between views of its users to government which is supposed to take care of that "diversity" stuff.

I don't want to get in to the Gratipay issue, or ones like it, in this place: this is a bug report, and I believe we've achieved consensus on whether or not the issues raised here need to be addressed. If a discussion about Gratipay is something you want to pursue, you're welcome to email me and we can talk about it further.

@dstufft, I think we're done here. =)

**Comment by dstufft** [comment] 2016-03-20 13:57
I've filed #1035 to deal with the specific issue of the copyright footer. I'm closing this issue since all of the other contents of it are by design and will not be changing.

**Closed by dstufft** 2016-03-20 13:57 UTC

**Comment by techtonik** [comment] 2016-03-20 16:47
> No, the license is simply saying that it does not grant that right, not that it forbids it being granted in any other way.

It that doesn't affect anything, why bloat the license text with that at all?

> If a discussion about Gratipay is something you want to pursue, you're welcome to email me and we can talk about it further.

Maybe, but I am afraid it can't be helped.
