### ISSUE TITLE
Disambiguate "OSI Approved :: BSD License"

### ISSUE THREAD

**Issue by dereckson** [pypa/warehouse#10871] opened 2022-03-06 11:26 UTC
**What's the problem this feature will solve?**
Currently, the classifiers allow to declare a software licensed under "BSD License".

Other frameworks like SPDX offers BSD-2-Clause and BSD-3-Clause, the two most used "BSD" licenses.

This ambiguity have impact to automated external tools: I've uploaded a package licensed under BSD-2-Clause, and external service libraries.io offers to generate a machine-readable properties file offering `license_spdx: BSD-3-Clause`.

**Describe the solution you'd like**
* "OSI Approved :: BSD License"
* "OSI Approved :: BSD License (3-Clause)"
* "OSI Approved :: BSD License (2-Clause)"

**Additional context**
https://en.wikipedia.org/wiki/BSD_licenses#Terms details the different n-Clause

**Comment by di** [comment] 2022-03-06 14:59
Duplicate of https://github.com/pypa/trove-classifiers/issues/17.

**Closed by di** 2022-03-06 14:59 UTC
Labels: feature request
