### ISSUE TITLE
Per-Project RSS feed

### ISSUE THREAD

**Issue by tritium21** [pypa/warehouse#5612] opened 2019-03-23 04:38 UTC
**What's the problem this feature will solve?**

Currently, if a user of Pypi wants to be notified of new releases or uploads for projects they care about, they either have to use the updates feed for all of pypi, or a third party service which typically requires outside access to their code repositories.

For most open source projects, this is fine - just point libraries.io at your github repo, job done.  For private or proprietary codebases, this is a bit more problematic (not insurmountable, but not ideal).

I believe that fetching the global updates feed is also non-ideal in that it would be easy to miss an update to the projects you care about if you don't tune your poll rate precisely to the upload cadence of pypi.

**Describe the solution you'd like**

I believe that pypi could provide per-project update feeds, so the user can subscribe to the feeds of the packages they care about, and none of the ones they do not.

**Additional context**

This is different from #2551 in that that request is asking for the current feeds to be updated with each upload, even to existing versions.  This request is to offer a restricted RSS feed only for a single project.

**Comment by tritium21** [comment] 2019-03-24 09:56
s/package/project/ to better match intentions

**Comment by di** [comment] 2019-03-27 17:46
Thanks for the request. This is a duplicate of #1683.

**Closed by di** 2019-03-27 17:46 UTC
