### ISSUE TITLE
not able to install celery with pip

### ISSUE THREAD

**Issue by ganeshsingamaneni** [pypa/warehouse#5266] opened 2019-01-09 06:43 UTC
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

```
(venv) ganesh@ganesh-Latitude-E6420:~/learning/saleor$ pip install celery
Collecting celery
  Using cached https://files.pythonhosted.org/packages/e8/58/2a0b1067ab2c12131b5c089dfc579467c76402475c5231095e36a43b749c/celery-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: pytz>dev in /home/ganesh/learning/venv/lib/python3.6/site-packages (from celery) (2018.9)
Collecting kombu<5.0,>=4.2.0 (from celery)
  Using cached https://files.pythonhosted.org/packages/44/5d/a4162de3033be4b42e59ee5101de92b218a6b0a943de9cbe8bab5c45479a/kombu-4.2.2.post1-py2.py3-none-any.whl
Collecting billiard<3.6.0,>=3.5.0.2 (from celery)
Exception:
Traceback (most recent call last):
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 728, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 582, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/ganesh/learning/venv/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 467, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jamadden** [comment] 2019-01-09 14:32
Although this could conceivably be a bug with warehouse and corrupted distributions, I cannot reproduce it. I suspect it's more likely that there was a network error and you received bad data, or a proxy between you and warehouse did. Can you try installing without using the cache? i.e., `pip install --no-cache-dir celery`

```
$ pip install celery
Collecting celery
  Downloading https://files.pythonhosted.org/packages/e8/58/2a0b1067ab2c12131b5c089dfc579467c76402475c5231095e36a43b749c/celery-4.2.1-py2.py3-none-any.whl (401kB)
    100% |████████████████████████████████| 409kB 11.7MB/s
Requirement already satisfied: pytz>dev in ./lib/python3.6/site-packages (from celery) (2018.9)
Collecting billiard<3.6.0,>=3.5.0.2 (from celery)
  Downloading https://files.pythonhosted.org/packages/8b/b7/c2fe04f2522bb02d044347734eeda3ff5c7a632fa7d0401530a371ba73db/billiard-3.5.0.5.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 4.4MB/s
Collecting kombu<5.0,>=4.2.0 (from celery)
  Downloading https://files.pythonhosted.org/packages/44/5d/a4162de3033be4b42e59ee5101de92b218a6b0a943de9cbe8bab5c45479a/kombu-4.2.2.post1-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 6.2MB/s
Collecting amqp<3.0,>=2.1.4 (from kombu<5.0,>=4.2.0->celery)
  Downloading https://files.pythonhosted.org/packages/7f/cf/12d4611fc67babd4ae250c9e8249c5650ae1933395488e9e7e3562b4ff24/amqp-2.3.2-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 19.2MB/s
Collecting vine>=1.1.3 (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.2.0->celery)
  Downloading https://files.pythonhosted.org/packages/62/dd/e30f828a39914626d67876b987d6fc47616b64de680cd0f746fc9c8aab47/vine-1.2.0-py2.py3-none-any.whl
Building wheels for collected packages: billiard
  Running setup.py bdist_wheel for billiard ... done
  Stored in directory: /Users/jmadden/Library/Caches/pip/wheels/b8/72/0e/39ecdedc4cfc45b693a623732e40dbd4cff5ea5e11775ee591
Successfully built billiard
Installing collected packages: billiard, vine, amqp, kombu, celery
Successfully installed amqp-2.3.2 billiard-3.5.0.5 celery-4.2.1 kombu-4.2.2.post1 vine-1.2.0
```

**Comment by ewdurbin** [comment] 2019-01-14 13:44
I'm also unable to reproduce. Are you still seeing the same behavior, @ganeshsingamaneni?

**Comment by pradyunsg** [comment] 2019-01-23 14:39
I think this is likely either a corrupted download / cache entry.

**Comment by brainwane** [comment] 2019-03-14 15:42
Since we've been unable to reproduce this, I'm closing this -- @ganeshsingamaneni if you're still running into this, please do re-open this bug and share details. Thanks!

**Closed** 2019-10-28 16:15 UTC
