### ISSUE TITLE
ordering changed when going to a second page

### ISSUE THREAD

**Issue by ziyangczi** [pypa/warehouse#9679] opened 2021-06-16 17:20 UTC
**Describe the bug**
When scrolling to a second page, the underlying ordering seems to have changed occasionally, which resulted in missing and/or duplicate entries across pages

**Expected behavior**
The underlying ordering should not change across multiple pages, or at least have a way to trach search sessions so as to preserve a specific ordering to allow users to see the full list of search results after browsing all pages.

**To Reproduce**
We run the query: 
https://pypi.org/search/?c=Framework+::+napari&page=1
https://pypi.org/search/?c=Framework+::+napari&page=2
etc, and sometimes a package would show up on page 2 again after showing up on page 1, while some of the packages would be missing, leading to inconsistency in the overall search result depending on the time of the query.

**My Platform**
I believe this is not platform-specific.

**Additional context**
N/A

**Comment by di** [comment] 2021-06-16 17:23
Thanks for the report! This is a duplicate of #4006.

**Closed by di** 2021-06-16 17:23 UTC
Labels: bug :bug:
