### ISSUE TITLE
Replace "pip" with "pip3" on linux systems

### ISSUE THREAD

**Issue by PROgramJEDI** [pypa/warehouse#7897] opened 2020-05-06 17:44 UTC
I recommend replacing only the string when attempting to install some packages on different operating systems.

For example, on windows, installation of a pip package would probably look like this:
```pip install package_name```

while on Linux, it would be like this:
```pip3 install package_name```

I think it would save some begginers a lot of time searching for the issue solution, by just finding the operating system of the user, and producing different strings according to that.

**Comment by di** [comment] 2020-05-06 19:53
Closing this as a duplicate of https://github.com/pypa/warehouse/issues/1563, but thanks for the report!

**Closed** 2020-05-06 19:54 UTC
