### ISSUE TITLE
Uploaded version listed as latest on version-specific page, but not updating in project listing

### ISSUE THREAD

**Issue by tyarkoni** [pypa/warehouse#8270] opened 2020-07-15 18:08 UTC
I just uploaded a new version of a package (pliers 0.4.0) to PyPI; I had no trouble with the upload, and haven't changed anything packaging-related since 0.3.0 as far as I know. I get the following rather strange behavior:

* https://pypi.org/project/pliers/0.4.0/ correctly lists 0.4.0 as the latest version
* https://pypi.org/project/pliers/ points to 0.3.0 and says that 0.3.0 is the latest verison
* The release history on the main project page doesn't show 0.4.0 at all.
* The release history under the version 0.4.0 page *does* show 0.4.0 as the latest version.
* The 0.4.0 release is not visible to pip.

I've searched the board, but can't find anything that seems relevant other than #6990, which suggests a caching issue that's been fixed. It's been more than an hour since the upload, so it doesn't seem like this is what's going on.

The only other thing I can think of is that the project currently contains no description. That's something I can (and should) easily remedy, but doesn't seem like a likely culprit unless PyPI now requires releases to have descriptions and didn't at the time of the last release (June 2019).

**Comment by dstufft** [comment] 2020-07-15 18:10
I'm guessing this was broken by https://github.com/pypa/warehouse/pull/8269 which is causing purges to fail right now in sentry.

**Comment by tyarkoni** [comment] 2020-07-15 18:12
Got it, thanks. I'll check back in a few hours and will close if it's resolved.

**Comment by Metalkiler** [comment] 2020-07-15 18:17
I was getting scared that my package was not being updated by my fault since I launched the version 2.0.0 of my package (cane) and it lists 0.0.1.7.6.2 as the lastest one

**Comment by di** [comment] 2020-07-15 18:20
This should be fixed by #8271. The issue is that CDN purges were temporarily failing.

If you find a page that is seemingly out of date, you can force a purge with:

```
$ curl -XPURGE https://pypi.org/<rest of the URL to the page>
```

Otherwise these should naturally fall out of the cache over the next 24 hours.

**Closed by di** 2020-07-15 18:20 UTC

**Comment by PatMyron** [comment] 2020-07-15 20:18
@di seems to be [issues beyond outdated pages](https://github.com/aws-cloudformation/cfn-python-lint/issues/1624)

**Comment by dstufft** [comment] 2020-07-15 20:20
You might have to PURGE ``https://pypi.org/simple/cfn-lint/`` as well.

**Comment by Metalkiler** [comment] 2020-07-15 20:49
My package still says the same if you check https://pypi.org/simple/cane/#description

Although I released a cane2.0.0 but it is saying that not exists

**Comment by di** [comment] 2020-07-15 21:03
@Metalkiler I just ran `curl -XPURGE https://pypi.org/simple/cane/` and it's now updated.

**Comment by brainwane** [comment] 2020-08-05 18:05
Per http://kafka.dcpython.org/day/pypa/2020-08-01 a similar issue happened to someone a few days ago. Should we add the `curl` command to some user help docs? Or investigate the CDN further?
