### ISSUE TITLE
Organization level account

### ISSUE THREAD

**Issue by santaimpersonator** [pypa/warehouse#8280] opened 2020-07-16 20:16 UTC
**What's the problem this feature will solve?**
This feature would provide additional project management of collaborators to organizations/companies. Similar to the organization accounts that GitHub provides:

> *"Organizations are shared accounts where groups of people can collaborate across many projects at once. Owners and administrators can manage member access to the organization's data and projects with sophisticated security and administrative features."*

For additional context, see the link for GitHub organization accounts, below.

**Describe the solution you'd like**
Th ability to manage collaborators on individual projects and broadly across all projects... a higher level of collaborator management/access.

**Additional context**
[GitHub Organization Accounts](https://docs.github.com/en/github/getting-started-with-github/types-of-github-accounts#organization-accounts)

-***"Please and thank you!"***

**Comment by di** [comment] 2020-07-16 20:18
Thanks for the request! This is a duplicate of #201.

**Closed by di** 2020-07-16 20:18 UTC

**Comment by santaimpersonator** [comment] 2020-07-16 20:20
@di Ahh... sorry about that. I should have scrolled back further when searching for "organization".
