### ISSUE TITLE
2FA: Use a better name and logo for in-app representation

### ISSUE THREAD

**Issue by phildini** [pypa/warehouse#5809] opened 2019-05-07 17:03 UTC
* **Date @ Event:** 5/7/2019 @ PyCon Cleveland Sprints
* **Scenario:** Enabling 2FA in Duo
* **OS environment:** iPhone
* **Things you used:** warehouse
* **Python version and origin:** n/a

## Please highlight your log using this legend:
- [ ] :heart_eyes: Yay, this is awesome
- [x] :frowning: This is a little annoying, I'm frustrated
- [ ] :rage: I'd quit if I weren't specifically trying to improve things.

## What were you trying to do, and what didn't work?
So, I was trying to add PyPI 2FA to my account, and using Duo as my authenticator app. Everything worked ok, but the entry in Duo came up as just my user name and the code. No site identifier, no logo, nothing.

## Ideally, what should have happened instead?
I have seen with other sites (like github) a site name and a logo show up in the entry in Duo. I'm not certain if this is supported by the TOTP spec, or requires registering with Duo, or what, but it would really help when I'm staring at a list of entries and trying to remember which is PyPI.

**Comment by dstufft** [comment] 2019-05-07 17:04
I think that this has to come from Duo? I'm not aware of anything in the TOTP spec that adds it, but I might be entirely wrong on that. Leaving this open until we get that figured out for sure.

**Comment by di** [comment] 2019-05-07 17:14
cc @mschwager

**Comment by mschwager** [comment] 2019-05-07 18:47
You can edit the account name and icon in the account's settings within the Duo Mobile app. I'm not sure if you get there the same way on iOS, but on Android you long-press the account in the list then press "Edit Account".

As far as icons go, we currently have a hard-coded list of available icons, and PyPI hasn't been added yet. There is an existing feature request :+1:

**Comment by di** [comment] 2019-05-07 19:45
Closing as there's nothing for us to do here. Thanks all!

**Closed by di** 2019-05-07 19:45 UTC
Labels: requires triaging

**Comment by mschwager** [comment] 2019-05-20 20:47
Just a heads up - we plan on automatically detecting PyPI as a third-party account in Duo Mobile. What this means is, when a Duo Mobile user scans the QR code, it will automatically show the PyPI logo and display "PyPI" as the account name rather than a generic account and the user's email address (unless they have multiple accounts under the same service provider).

However, I think we may need some help to support this. The way this is typically done is by detecting the service provider by their issuer name. E.g. the `issuer_name` argument to `generate_totp_provisioning_uri` in [otp.py](https://github.com/pypa/warehouse/blob/master/warehouse/utils/otp.py). There is a bit of confusion about what this defaults to, though. The function kwarg defaults to `PyPI`, whereas it appears that [warehouse/config.py](https://github.com/pypa/warehouse/blob/master/warehouse/config.py) defaults `site.name` to `Warehouse` which gets used in [warehouse/manage/views.py](https://github.com/pypa/warehouse/blob/master/warehouse/manage/views.py).

IMO it'd be good to rectify the issuer name in these two places so mobile apps can rely on a consistent value. I think the best path forward would be removing the kwarg specification in `views.py` so that it uses the default value (`PyPI`).

Thoughts?

**Comment by di** [comment] 2019-05-20 20:55
I agree the `issuer_name="PyPI"` kwarg should probably be removed.

This value will differs depending on which site 2FA is being enabled for, but you can depend on these values being consistent:

* https://pypi.org: `PyPI`
* https://test.pypi.org: `TestPyPI`
* local development: `Warehouse` (but I don't think Duo needs to handle this)

**Comment by mschwager** [comment] 2019-05-20 21:03
Roger that - thanks!

**Comment by brainwane** [comment] 2019-05-23 03:19
Is #5894 a duplicate of this? (cc @signop)

**Comment by mschwager** [comment] 2019-05-23 21:57
@brainwane Yes, I'd say so.

> More helpful would be, e.g., test.pypi.org-$username to show which PyPI (and really which site) the account is for, AND which account it is.

This will show up as "PyPI" with the username underneath and the PyPI logo to the left, e.g.

![image](https://user-images.githubusercontent.com/1724818/58289247-23fcec80-7d73-11e9-9c80-8a3673d4707f.png)

(https://guide.duo.com/third-party-accounts)

**Comment by signop** [comment] 2019-05-23 23:01
Sorry for my slow reply, yep, #5894 looks like it was from me trying to describe this same thing. Having PyPI (or Test PyPI) next to the account is exactly what I was hoping for. Thanks!

**Comment by mschwager** [comment] 2019-07-09 18:56
Heads up, the latest version of Duo Mobile now includes an icon option for PyPI warehouse:

![pypi](https://user-images.githubusercontent.com/1724818/60915286-79288b00-a259-11e9-8b95-e8b9bdaaafc7.png)

Shoutout to @robsmall for helping out here!
