### ISSUE TITLE
Cannot find a package in search: boolean.py

### ISSUE THREAD

**Issue by pombredanne** [pypa/warehouse#1139] opened 2016-04-29 07:08 UTC
See https://github.com/bastikr/boolean.py/issues/44
A simple search for `boolean.py` return no results at all and this is the package name.
A simple search for `boolean`  does not return boolean.py.
The package is there alright: https://pypi.python.org/pypi/boolean.py

**Comment by sigmavirus24** [comment] 2016-04-29 15:27
https://pypi.io/search/?q=boolean.py does seem to bring up the package.

**Comment by pombredanne** [comment] 2016-04-29 17:52
@sigmavirus24 thanks Ian. I may have made a confusion with the current Pypi and filed this issue in the wrong place

**Comment by dstufft** [comment] 2016-04-30 19:45
Going to close this, since it's a problem with legacy PyPI (and the problem is basically that search is known broken on legacy PyPI at the moment :( )

**Closed by dstufft** 2016-04-30 19:45 UTC
