### ISSUE TITLE
Link to yank release from manage  UI

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8450] opened 2020-08-18 15:58 UTC
Currently when displaying a yanked release at `https://pypi.org/manage/project/<project_name>/releases/`, the table does not link to the yanked release like it does for non-yanked releases:

![image](https://user-images.githubusercontent.com/294415/90536399-9fe61000-e141-11ea-96dd-1e4da3c4de29.png)

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Comment by hmalik88** [comment] 2020-09-11 20:02
Hi! Can I claim this issue? @di

**Comment by di** [comment] 2020-09-11 20:08
Hi @hmalik88, we don't assign issues but you're welcome to work on this. As far as I'm aware nobody else is.

**Comment by hmalik88** [comment] 2020-09-11 20:46
Sounds good, this is my first OS contribution. I think I have this under control. I'll submit a PR soon. Thanks!

**Comment by hmalik88** [comment] 2020-09-12 03:25
Hi @di , I reached out on freenode and got disconnected, not sure if the message persisted. 

I believe the fix for this issue lies in the [warehouse/templates/manage/releases.html](https://github.com/pypa/warehouse/blob/master/warehouse/templates/manage/releases.html) file in lines 36-41. The release model has a yanked property. I wanted to confirm if the issue brought up is indeed unintended behavior as the logic in the code explicitly checks for that yanked property. If so, I can fix it and add in a test. Please let me know, thanks!

**Comment by di** [comment] 2020-09-14 14:42
Yes, you're right, you would remove the conditional on that line. We'll probably also need to update the page it links to, as right now it assumes the release hasn't been yanked and displays options like "Yank this release".

We don't have tests for our frontend that would capture this, so you likely won't have to update any.

**Comment by hmalik88** [comment] 2020-09-19 21:47
Hi @di , can you please review and provide any feedback if I need to make changes? Thanks!

**Closed** 2020-09-21 14:49 UTC
Labels: UX/UI, good first issue
