### ISSUE TITLE
Untie the version used for "pip install xxx" from the in-progress release of the next version of xxx

### ISSUE THREAD

**Issue by arigo** [pypa/warehouse#6843] opened 2019-10-15 15:17 UTC
**What's the problem this feature will solve?**
We cannot atomically release a new version of our software.  Consider a user trying to run "pip install xxx" after we have uploaded the source but before the corresponding wheels.  He will unexpectedly download the new version in source format, and this source code might not compile on his machine because he doesn't have the full development environment and dependencies installed.

**Describe the solution you'd like**
I would like to be able to mark a specific version as "default".  It would be this version that is used by a plain "pip install xxx".  With this, I would be able to complete and test the release before switching the "default" to it.  It should be an opt-in behavior, of course; if the "default" version is not explicitly set then it's the most recent version like now.

This is just an idea; anything that allows atomic releases would be enough, however cumbersome it is.  An alternative would be to prefer a wheel from the previous release over the source code from the current release (again, only if the project is configured to do so).

**Additional context**
The time gap is usually small, but it extended for three hours this morning when releasing the new version of cffi.  It was enough time to get multiple reports of angry users, on IRC, mailing list, and several issues (including https://bitbucket.org/cffi/cffi/issues/424/please-rollback-to-1123).

**Comment by arigo** [comment] 2019-10-15 15:20
Yet another solution: we would upload the new version to TestPyPI, and when it's complete transfer that atomically to PyPI.

**Comment by di** [comment] 2019-10-15 15:43
I think this is probably a duplicate of #726, would you mind adding your thoughts to that issue?

**Comment by arigo** [comment] 2019-10-15 15:49
Yes, I just noticed and wrote a link from #726 to here.  Do you still want me to consolidate my thoughts into #726?

**Comment by di** [comment] 2019-10-16 12:57
Please do! I'm going to close this issue in the meantime, but thanks for the feature request.

**Closed by di** 2019-10-16 12:57 UTC
