### ISSUE TITLE
Regexp support for api query/search.

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/warehouse#8765] opened 2020-10-29 14:44 UTC
Hi,

It seems that the currently available APIs exposed by [warehouse](https://warehouse.readthedocs.io/api-reference/index.html#available-apis-datasets) doesn't  support regexp for query/search.

Could you please add this feature in the future?

Regards,
HY

**Comment by di** [comment] 2020-10-29 21:48
Duplicate of #5231.

**Closed by di** 2020-10-29 21:48 UTC
