### ISSUE TITLE
Improve static asset build

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#7712] opened 2020-04-01 20:20 UTC
It would be great to improve the performance of the building of static assets in development.

Currently, when I make an update to the SCSS files, it's taking around 15 seconds to rebuild before I can refresh the page and check my work - this is very frustrating!

**Comment by yeraydiazdiaz** [comment] 2020-04-02 08:10
Related https://github.com/pypa/warehouse/issues/6141

**Comment by di** [comment] 2020-04-02 15:58
Actually yeah, just going to call this a duplicate of #6141!

**Closed by di** 2020-04-02 15:58 UTC
Labels: developer experience, javascript
