### ISSUE TITLE
Update description on https://pypi.python.org/pypi since new endpoint

### ISSUE THREAD

**Issue by lmazuel** [pypa/warehouse#2251] opened 2017-07-27 22:46 UTC
Not sure where I should fill this, but I presume someone here ( @dstufft ? :)) can help if it's not the right place :)
Since the new endpoint, the "edit" button on https://pypi.python.org/pypi to edit the PKG-INFO is broken. I end with this sign when I hit the "Update information" button:
```text
Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)
```

At the same time, update in warehouse is not available: https://github.com/pypa/warehouse/issues/2170

I looked into twine and packging info website, but was unable to find a way to update only the description in the PKG-INFO.

What is the suggested solution now?

Thanks!

**Comment by gtback** [comment] 2017-07-30 02:51
Possible duplicate of (or at least related to) #2170?

**Comment by dstufft** [comment] 2017-07-30 03:32
Yea, this is just a duplicate of #2170. I'll try to update that ticket either later tonight or tomorrow with more information.

**Closed by dstufft** 2017-07-30 03:32 UTC

**Comment by lmazuel** [comment] 2017-08-09 16:43
@gtback @dstufft I humbly think it's not a duplicate, since this is two different websites (note that I mentioned #2170 too in my text). Not being able to update **any more** description on https://pypi.python.org/pypi is one issue, not being able to update **yet** description on https://pypi.org/ is another one.
