### ISSUE TITLE
The expected behavior when using multiple options of the same type of filter is to include more.

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [pypa/warehouse#10743] opened 2022-02-13 23:35 UTC
When I click on Alpha and Beta under Development Status I'm expecting to get more projects instead of less. It doesn't make sense for a project to be in Alpha and Beta so it shouldn't be using and logic.

**Comment by di** [comment] 2022-02-13 23:52
Duplicate of #5765.

**Closed by di** 2022-02-13 23:52 UTC
Labels: bug :bug:
