### ISSUE TITLE
Cannot find specific PIP packages using pip search

### ISSUE THREAD

**Issue by bbloks** [pypa/warehouse#8130] opened 2020-06-18 09:04 UTC
**Describe the bug**
Using the `pip search` function I am not able to find specific packages. Notably some of these packages are main packages like Flask and Django. I am able to install them on the virtual environment, however searching for them does not show the package and its latest version. 
I thought it may have to do with a limit in search results, however I have found no information that the results of `pip search` are actually limited, of if so, there would be a way to set no limit to the results. For example when I search for the package `Flask` which has current version of `1.1.2` as writing this issue, I get the following result:

```pip search Flask```

```
Flask-SimpleMDE (0.3.0)     - Flask-SimpleMDE - a Flask extension for SimpleMDE
Flask-Pure (0.5)            - Flask-Pure - a Flask extension for Pure.css
Flask-OrientDB (0.1)        - A Flask extension for using OrientDB with Flask
Flask-ElasticUtils (0.1.7)  - ElasticUtils for Flask
flask-helloworld (1.0.0)    - Flask Helloworld
sockjs-flask (0.3)          - SockJs for Flask
Flask-Quik (0.1.1)          - Quik for Flask
Flask-BDEA (0.1.0)          - Flask-BDEA
Flask-PubSub (0.1.0)        - Flask-PubSub
Flask-Waitress (0.0.1)      - Flask Waitress
flask-live (0.0.1)          - Flask Live
flask-zs (0.0.24)           - A helpers for Flask.
Flask-Stripe (0.1.0)        - Flask-Stripe
Flask-Helper (0.19)         - Flask Helper
flask-ws (0.0.1.0)          - Websocket for flask.
Flask-MDE (1.2.0)           - Pagedown for Flask
Flask-Watson (0.1.0)        - Flask-Watson
Flask-FileRev (0.1.0)       - Flask-FileRev
Flask-Ext (0.1)             - Extensions of Flask
Flask-Weixin (0.5.0)        - Weixin for Flask.
Flask-GripControl (0.0.1)   - Flask GripControl
Flask-TinyMce (0.1.6)       - flask tinymce
Flask-SRI (0.1.0)           - Flask-SRI
Flask-Intercom (0.1.0)      - Flask-Intercom
Flask-SPF (0.0.0)           - Flask-SPF
flask-toolbox (0.0.2)       - A flask toolbox.
Flask-Turbolinks (0.2.0)    - Turbolinks for Flask.
Flask-Shopify (0.2)         - Shopify Flask
Flask-TaskTiger (0.0.1)     - Flask TaskTiger
flask-ypaginate (0.1.3)     - Pagination for Flask
flask-abort (0.0.1)         - flask abort
Flask-Mustache (0.4.1)      - Mustache for Flask
Fifty-Flask (1.4.0)         - Flask enhancements.
Flask-OAuthlib (0.9.5)      - OAuthlib for Flask
Flask-Chargebee (0.0.1)     - Flask-Chargebee
Flask-Keen (0.1.0)          - Flask-Keen
Flask-NextCaller (0.1.0)    - Flask-NextCaller
Flask-Gears (0.2)           - Gears for Flask
Flask-Clearbit (0.1.0)      - Flask-Clearbit
Flask-FontAwesome (0.1.4)   - FontAwesome for Flask
flask-mico (0.2.0)          - flask mico
Flask-AutoIndex (0.6.6)     - The mod_autoindex for Flask
airbrake-flask (1.0.7)      - airbrake-flask - Airbrake client for Python Flask
Flask-GeoIP (0.1.3)         - Flask-GeoIP -------------  Simple Flask extension for pygeoip.
Flask-Diced (0.3)           - Flask-Diced - CRUD views generator for Flask
Flask-RESTive (0.0.3)       - Flask RESTive is a REST API Flask extension based on Flask-RESTful & Marshmallow.
Flask-LoginManager (1.1.6)  - Flask-Loginmanager supports multiple roles and permissions for Flask, inspired by Flask-Login
Flask-FlatPagesCut (0.5.1)  - Flask-FlatPagesCut is fork Flask-FlatPages (Provides flat static pages to a Flask application)
flask-lesscss (0.9.1)       - A small Flask extension that adds LessCSS support to Flask.
flask-shell (0.1.3)         - Flask extension to improve shell command for the Flask CLI.
flask-stylus2css (0.1)      - A small Flask extension that adds Stylus support to Flask.
flask-coffee2js (0.1.2)     - A small Flask extension that adds CoffeScript support to Flask.
Flask-Collect (1.3.2)       - Flask-Collect -- Collect static files in Flask application
flask-filters (0.3)         - The Flask Filter to use with flask-restful and Relational DB
Flask-Shelve (0.1.1)        - Shelve support for Flask
Flask-CKEditor (0.4.4.1)    - CKEditor integration for Flask.
Flask-Triangle (0.5.4)      - Integration of AngularJS and Flask.
Flask-Funnel (0.1.10)       - Asset management for Flask.
flask-logsocketio (0.1.4)   - Flask LogSocketIo module
flask-serial (1.1.0)        - Flask extension for the Serial
flask-discoverer (0.1.4)    - Flask API autodiscovery
flask-snow (0.2.8)          - Pysnow extension for Flask
Flask-Triangle3 (0.5.3)     - Integration of AngularJS and Flask.
Flask-wechatpy (0.1.3)      - wechatpy for flask extension
Flask-Vises (2.1.4)         - A Flask scaffold library
Flask-PyFCM (0.1.1)         - Flask extension for PyFCM
Flask-sshtunnel (0.1b2)     - sshtunnel extension for flask
Flask-Enterprise (1.0)      - Enterprise capabilities for Flask
Flask-Flarf (0.0.5)         - Flask request filtering
Flask-Failsafe (0.2)        - A failsafe for the Flask reloader
Flask-Testing (0.8.0)       - Unit testing for Flask
Flask-wangEditor (0.0.3.2)  - wangEditor integration for Flask.
Flask-Sixpack (0.0.1)       - Flask wrapper for Sixpack
Flask-OpenID (1.2.5)        - OpenID support for Flask
Flask-Edits (0.8)           - Editable Content in Flask
Flask-CuttlePool (0.2.1)    - A Flask extension for CuttlePool
Flask-Zero (0.9.6)          - Qiniu Storage for Flask
Flask-Breve (0.2)           - Breve templating with Flask
Flask-mongobit (0.3.0)      - MongoBit support in Flask
Flask-SaeStorage (0.9.0)    - SAE Storage for Flask
Flask-Navigation (0.2.0)    - The navigation of Flask application.
Flask-Passlib (0.1)         - Flask extension for passlib
Flask-Slack (0.1.5)         - Slack extension for Flask.
Flask-ZMQ (0.1.2)           - Flask extension for ZMQ
Flask-Autodoc (0.1.2)       - Documentation generator for flask
flask-fast (0.0.1.dev0)     - Flask-fast. It's fast.
Flask-CAS (1.0.2)           - Flask extension for CAS
Flask-SAML (0.4.3)          - Flask SAML integration
flask-tat (0.0.10)          - Flask TAT client
flask-authentic (0.0.11)    - Flask Authentic Extension
nailpack-flask (0.1.0)      - Flask support for nails
Flask-Avatar (0.1.3)        - To generate avatar for flask
flask-adh (0.1)             - flask admin antd
flask-now (0.2.2)           - Flask App Generator
Flask-Storm (0.2.0)         - Storm integration for Flask.
Flask-Config (0.2.1)        - Flask configuration class
flask-blitzdb (0.1)         - Flask extension for blitzdb
Flask-RBAC (0.3.0)          - RBAC support for Flask
castle-flask (0.0.1)        - A Flask client for Castle.io
flask-keycloak (1.1.0)      - flask integration with keycloak
```
In this list there is no package called `Flask` shown.
I encounter a similar issue when searching for `django`, using `pip search django` I do not get the latest version of `django` itself.

**Expected behavior**
I would expect to see `Flask` in the results, something like:

```pip search Flask ```, returns:
```
...
Flask (1.1.2)     - A simple framework for building complex web applications.
....
```

**To Reproduce**
- Create a virtual environment: `python3 -m venv env`
- Activate virtual environment: `source venv/bin/activate`
- Search for specific package: `pip search Flask`

**My Platform**
- Ubuntu 18.04.3 LTS
- pip 20.1.1
- python 3.6.9

**Additional context**
n.a.

**Comment by di** [comment] 2020-06-18 16:50
Duplicate of https://github.com/pypa/warehouse/issues/5506.

**Closed by di** 2020-06-18 16:50 UTC
