### ISSUE TITLE
User is not recieving the confirmation email from PyPI

### ISSUE THREAD

**Issue by ng-cube** [pypa/warehouse#11683] opened 2022-06-27 06:58 UTC
**Describe the bug**

Wanted to register an account in PyPI and activate it, but no email was sending to my primary account or optional account

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment] 2022-06-27 14:23
Duplicate of #11682.

**Closed by di** 2022-06-27 14:23 UTC
Labels: requires triaging, bug :bug:
