### ISSUE TITLE
How to remove myself as a collaborator on a project?

### ISSUE THREAD

**Issue by inklesspen** [pypa/warehouse#7854] opened 2020-04-14 22:51 UTC
I am currently marked as a collaborator on three projects I don't want to be. I am not the sole collaborator on any of them. However, the "Remove" button next to my name is grayed out. How can I remove myself from the projects?

**Comment by yeraydiazdiaz** [comment] 2020-04-26 10:53
Hello @inklesspen, I believe only owners can remove collaborators in PyPI at the moment. I feel it's a feature requested before but I can't find the issue right now.

**Comment by pradyunsg** [comment] 2020-04-26 15:17
https://github.com/pypa/warehouse/issues/5790 is what you're looking for @yeraydiazdiaz. :)

**Comment by inklesspen** [comment] 2020-04-26 17:23
I _am_ an owner on the project, though, actually. And I don't want to be.

![image](https://user-images.githubusercontent.com/11397/80314712-f05aeb80-87a7-11ea-9a35-ec450087aa84.png)

**Comment by inklesspen** [comment] 2020-04-26 17:24
So looks like it's #4729.

**Comment by di** [comment] 2020-04-26 19:57
Yep! Closing as a duplicate of #4729.

**Closed by di** 2020-04-26 19:57 UTC
Labels: feature request
