### ISSUE TITLE
Broken paging on the packages-with-classifier page

### ISSUE THREAD

**Issue by njsmith** [pypa/warehouse#5327] opened 2019-01-23 05:43 UTC
Here's a page of packages that have the `Framework :: Trio` classifier: https://pypi.org/search/?c=Framework+%3A%3A+Trio

There are more than 20, so some spill onto the next page. Let's click "next" to see them: https://pypi.org/search/?c=Framework+%3A%3A+Trio&page=2

...that's odd. All the packages listed on the second page are duplicates of packages listed on the first page. For example, as I write this, pynng is the first package listed on the first page, and also the second package listed on the second page.

It looks like by default, there's a drop-down set to "Order by: [Relevance]". If I switch it to "Order by: [Date last updated]", then that seems to fix things so that the second page lists items that are not listed on the first page.

I haven't checked whether this affects other search pages; it might be more general than just classifier-based searches.

**Comment by di** [comment] 2019-01-23 15:49
Thanks for the report! This is a duplicate of #4006.

**Closed by di** 2019-01-23 15:49 UTC
