### ISSUE TITLE
Package version inconsistency after new release

### ISSUE THREAD

**Issue by mackeyja92** [pypa/warehouse#5323] opened 2019-01-22 20:10 UTC
**Describe the bug**
A new version of a package is showing up in the search that is not able to be installed via pip.

**Expected behavior**
A new version of a package should not display in the search if it is not yet able to be installed.

**To Reproduce**
```
/ # pip search uvicorn
uvicorn (0.3.31)  - The lightning-fast ASGI server.
uvitools (0.0.4)  - A toolkit for Uvicorn.
/ # pip install uvicorn=="0.3.31"
Collecting uvicorn==0.3.31
  Could not find a version that satisfies the requirement uvicorn==0.3.31 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23, 0.3.24, 0.3.25, 0.3.26, 0.3.27, 0.3.28, 0.3.29, 0.3.30)
No matching distribution found for uvicorn==0.3.31
```

**My Platform**
`pip 19.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Additional context**
At the time of making this issue, the package had updated to version `0.3.31` 5 hours ago. 

https://pypi.org/project/uvicorn/0.3.31/

There are a few places where it is inconsistent.

- The release history page does _not_ show this version
- The search page _does_ show this version
- The description page does _not_ show this version.

This is very annoying when using tools like poetry because it uses the search endpoint to determine the latest release of a package but it won't be able to actually install the package.

**Comment by di** [comment] 2019-01-22 22:32
Looks like a small hiccup in our CDN cache purging mechanism. I manually purged the cache and 0.3.31 is now available everywhere.

Closing this as a duplicate of #4892, but thanks for reporting!

**Closed by di** 2019-01-22 22:32 UTC

**Comment by mackeyja92** [comment] 2019-01-22 22:34
Ah, thanks for doing that!
