### ISSUE TITLE
pypi.org compatibility with pip 1.5.4 

### ISSUE THREAD

**Issue by fbouliane** [pypa/warehouse#3280] opened 2018-03-15 23:41 UTC
With ubuntu 14.04, you are unable to use pip without using the `--allow-external pip` flag.

Currently, pip fails with :
```
Downloading/unpacking Flask
  Could not find any downloads that satisfy the requirement Flask
  Some externally hosted files were ignored (use --allow-external Flask to allow).
Cleaning up...
No distributions at all found for Flask
Storing debug log for failure in /root/.pip/pip.log
```

It seems to be due to the migration from pypi.python.org to pypi.org in a combination with pip 1.5.4 (the default pip available in ubuntu trusty repository).

To fix, it seems that newer pip doesn't have this problem so an update of the version of pip fixes the problem
`pip install --allow-external pip --upgrade -i https://pypi.org/simple  pip==9.0.1`

To reproduce the bug, you can use the dockerfile here
https://gist.github.com/fbouliane/5c2cad96766740bd229927dc4d2bb484

**Comment by ewdurbin** [comment] 2018-03-15 23:44
@fbouliane thank you for your report! indeed upgrading `pip` is likely the best solution, but may not be acceptable for some users. we'll take this into consideration as we plan the remainder of the migration.

**Comment by mmagin** [comment] 2018-03-16 00:00
Yeah, a lot of people are still using Ubuntu 14.04, this is going to cause a lot of pain.

**Comment by eastokes** [comment] 2018-03-16 00:02
Breaking all our ansible 14.04 builds here 😢

**Comment by ewdurbin** [comment] 2018-03-16 00:02
we use ubuntu 14.04 internally for much of the PSF infrastructure as well.

most of our Python stuff is installed in its own virtualenv that uses a modern pip. this obviously isn't tenable for most.

Another alternative is to set your index URL to https://pypi.org/simple/ directly.

**Comment by ewdurbin** [comment] 2018-03-16 00:03
Load tests are going well, and we'll likely be concluding them for the evening soon. This will need be addressed in some way.

**Comment by ewdurbin** [comment] 2018-03-16 00:06
load splitting is completed for the evening.

**Comment by ewdurbin** [comment] 2018-03-16 14:55
appears to have been addressed by #3290 we're splitting traffic again and I'm unable to reproduce

**Comment by fbouliane** [comment] 2018-03-16 16:08
It seems fixed !
Thanks for your help.

**Comment by ewdurbin** [comment] 2018-03-16 16:08
🎉

**Closed** 2018-03-16 16:08 UTC
Labels: help needed
