### ISSUE TITLE
API to get dependencies of old package versions 

### ISSUE THREAD

**Issue by hoodmane** [pypa/warehouse#9835] opened 2021-07-24 14:37 UTC
**What's the problem this feature will solve?**
Currently the https://pypi.org/pypi/{pkgname}/json API includes data about the requirements under `requires_dist` but it only includes the metadata for the most recent package version. The old releases are under `releases` but they have no requirements data. If `pip` decides on an old version of the package, then if possible it uses `LazyWheel` to load just the `dist-info` part of the wheel and read the requirements. Otherwise, it loads the entire wheel.

This seems needlessly complicated to me. I work on [Pyodide](https://github.com/pyodide/pyodide) and we have a small package manager and installer we call `micropip`. Because of the nature of the browser, packages will have to be installed on every page load, thus speed of dependency resolution is important. We have difficulties with range requests because pypi doesn't set the correct CORS headers on range requests pypa/conveyor#11. We can cache the dependencies of packages in the `IndexedDB` or other persistent stores to speed up subsequent loads.

**Describe the solution you'd like**
If CORS headers were included on responses to range requests (resolving pypa/conveyor#11), we could use the same `LazyWheel` strategy. This would be better than the current situation where we have to pause dependency resolution to wait for wheel download. 

However, it seems to me that any of the following options would be better:
1. Update https://pypi.org/pypi/{pkgname}/json so it returns dependencies of all old versions of packages, say under `.releases[version][wheel_index][dependencies]` or somewhere else.
2. Add separate endpoint that returns the dependencies of all versions of a package, or an endpoint that returns dependencies of some particular version.
3. An API to ask for just the `dist-info` part of a wheel.

This would benefit us at Pyodide, but also I believe that it would allow on the order of ~300 lines of LazyWheel related code to be removed from pip in favor of the more simple approach of having an API that returns the data needed as JSON.

**Comment by ewjoachim** [comment] 2021-07-25 11:14
> Add separate endpoint that returns the dependencies of all versions of a package, or an endpoint that returns dependencies of some particular version.
> An API to ask for just the dist-info part of a wheel.

I believe this would be discussed in https://github.com/pypa/warehouse/issues/8254

**Comment by hoodmane** [comment] 2021-07-25 13:56
Right, it was a bit hard for me to believe this didn't already exist. Thanks! I guess I should close this as a duplicate.

**Comment by ewjoachim** [comment] 2021-07-25 13:57
Well, if we decide to go through the route of your point number 1, then maybe this is not a duplicate :) Let's see what the other say.

**Comment by hoodmane** [comment] 2021-07-25 14:03
Right. I guess it would also be very helpful for us if https://github.com/pypa/conveyor/issues/11 were fixed and also if the range for the Metadata wheel were exposed in somewhere (just saying which range to grab would allow `LazyWheel` to be drastically simplified).

**Comment by di** [comment] 2021-08-10 17:46
Closing this as a duplicate of #8254.

**Closed by di** 2021-08-10 17:46 UTC
Labels: feature request
