### ISSUE TITLE
How to make new releases visible manually?

### ISSUE THREAD

**Issue by letmaik** [pypa/warehouse#2249] opened 2017-07-27 20:56 UTC
When I prepare a new release of one of my binary libraries (having 16 binary wheels currently) then I'd like to hide the new release until all wheels have been uploaded correctly (which happens via Travis CI and Appveyor jobs). In the old pypi I could at least hide the new release after the first file upload was made, but in the new pypi I can't modify anything, well, except the profile picture...

By not having this functionality there can be times when people get broken installs because only part of the wheels have been uploaded and pip then downloads the possibly already uploaded tar.gz source package and fails when building.

**Comment by dstufft** [comment] 2017-07-27 20:59
Hiding on legacy PyPI didn't hide it from pip, it only hid it in the UI, which is why we removed it, because it was just generally confusing to people. 

Ultimately though, I think that this is a duplicate of #726.

**Closed by dstufft** 2017-07-27 20:59 UTC
