### ISSUE TITLE
Pypi should not allow upload of files with a version mismatch

### ISSUE THREAD

**Issue by chaoflow** [pypa/warehouse#6260] opened 2019-07-25 17:43 UTC
**Describe the bug**
The current docutils [0.15.1](https://pypi.org/project/docutils/0.15.1/) release cannot be installed from source as the source tarballs version is 0.15.1.post1 instead of 0.15.1. Pypi should prevent such mismatches.

**Expected behavior**
Do not accept files where the file name version does not match the metadata version.

**To Reproduce**

**My Platform**

**Additional context**

**Comment by bertjwregeer** [comment] 2019-08-05 18:59
Similar to: https://github.com/pypa/warehouse/issues/5372

**Comment by di** [comment] 2019-08-06 00:11
Closing as a duplicate of #5372.

**Closed by di** 2019-08-06 00:11 UTC
Labels: feature request, needs discussion
