### ISSUE TITLE
Logged-in menu is missing without javascript

### ISSUE THREAD

**Issue by michael-k** [pypa/warehouse#4642] opened 2018-08-29 09:05 UTC
**Describe the bug**

We logged in to https://pypi.org/, having javascript from pypi.org enabled, but from ravenjs.com disabled, I cannot see the navigation for logged-in users.

Instead I still see `Log in` and `Register`.

Since I'm being redirected on login to https://pypi.org/manage/projects/, I can still navigate through all pages, and even logging out works when guessing https://pypi.org/account/logout/ correctly.

**Expected behavior**

I can navigate the site without having to enable javascript from a third party.

**To Reproduce**

Disable javascript from ravenjs.com (eg. with noscript)

**My Platform**

Firefox 61.0.2 with NoScript

**Additional context**

A test is missing for the menu: pypa/warehouse#2154

**Comment by di** [comment] 2018-08-29 15:04
Duplicate of #4336.

**Closed by di** 2018-08-29 15:04 UTC
