### ISSUE TITLE
Cannot remove API token

### ISSUE THREAD

**Issue by JokerQyou** [pypa/warehouse#7172] opened 2020-01-02 14:43 UTC
**Describe the bug**

I created an API token with a scope of my whole account, just to test and play with GitHub Actions. After that I want to remove it, and instead use a new API token with project scope. But I cannot remove it. Each time I try, it prompts for my account password, after entering the correct password, it says "Invalid credentials. Try again". See the screenshots:

![The password prompt](https://user-images.githubusercontent.com/1465267/71672338-96758680-2db0-11ea-8b73-83e26a53c5b2.png)

![After entering the correct password and confirming the deletion](https://user-images.githubusercontent.com/1465267/71672347-9aa1a400-2db0-11ea-8090-2bce30e78eba.png)

**Expected behavior**

After entering my account password for confirmation, the corresponding API token should be removed from my account.

**To Reproduce**

- Create an API token;
- Go back to "Account" page, from the API token list, use the "Option" button > "Remove" to try to remove this API token;

**My Platform**
I don't think client platform matters in this case. But I'm using Edge `79.0.309.56` on macOS `10.15.2`.

**Additional context**

I have 2FA enabled (TOTP).

**Comment by ewdurbin** [comment] 2020-01-02 15:36
thank you for reporting. this is a duplicate of #7143. I'm looking into this now but have been unable to reproduce.

**Closed by ewdurbin** 2020-01-02 15:36 UTC
