### ISSUE TITLE
Bulk adding of collaborators

### ISSUE THREAD

**Issue by potiuk** [pypa/warehouse#7967] opened 2020-05-17 12:24 UTC
**What's the problem this feature will solve?**
I have just created 58 packages for apache-airflow (we are splitting the releases into smaller)
and I need to add 6  collaborators (PMC team for apache-airflow) for all the projects. 

I would love to be able to do it in bulk

**Describe the solution you'd like**
Command line tool that would allow me to add collaborators in bulk (or a way to define group of collaborators).

**Comment by di** [comment] 2020-09-29 15:03
Thanks for the feature request! Closing as a duplicate of https://github.com/pypa/warehouse/issues/201 -- supporting groups/organizations is the way we'd like to support this use case in the future.

**Closed by di** 2020-09-29 15:03 UTC
Labels: APIs/feeds, feature request
