### ISSUE TITLE
Add a one time username change.

### ISSUE THREAD

**Issue by justengel** [pypa/warehouse#4144] opened 2018-06-08 15:11 UTC
**What's the problem this feature will solve?**
Users cannot change their username. Creating a new user will make the new username lose access and a reference to the packages that a user has created and maintained.

**Describe the solution you'd like**
Add a link on the pypi website under Account Settings to change a users username or send an email to someone who will allow the user to change their username. This will allow pypi maintainers to limit the number of times a person can change their username.

**Additional context**
Things change. When people start using pypi they may not be an established developer and pick random username. As they become more established they may want their username to reflect their profile across different websites or they may want their username to reflect a new domain name.

**Comment by di** [comment] 2018-06-08 15:16
Thanks for the feature request! This is a duplicate of #1190.

**Closed by di** 2018-06-08 15:16 UTC

**Comment by justengel** [comment] 2018-06-08 15:21
I should have guessed. Sorry. PyPi says that the username "cannot be changed" on the page. I thought that meant it was a specific long term decision. Thank you for pointing me to #1190
