### ISSUE TITLE
UI to view wheel and sdist content

### ISSUE THREAD

**Issue by uranusjr** [pypa/warehouse#7877] opened 2020-05-01 17:35 UTC
**What's the problem this feature will solve?**
@pfmoore, @pradyunsg and I were talking about dependency conflict debugging, and it came up as a topic that a significant number of users opt to “read setup.py” when they are looking for dependency information.

This is, however, currently quite awkward to do. The user either needs to find the project’s repository (e.g. GitHub) and hunt for the correct tag/commit, or download the distribution file and extract it manually. It is also difficult for pip to implement a feature to help with the process.

**Describe the solution you'd like**
A view that allows the user to view the contents of a given distribution (wheel or sdist), and read the content of a given file in the archive. The viewer can be a bare minimal `text/plain` page, but some basic features like line numbers would be very nice to have.

Each list view and file view should have a unique URL, e.g. I can paste a URL to the browser and read `setup.py` in `Django-3.0.tar.gz`, or the `METADATA` file of a wheel directly. This would be valuable for sharing package information and help with user support.

**Additional context**
N/A

**Comment by di** [comment] 2020-05-01 18:08
Is the goal here to inspect the metadata for a release, or to view arbitrary files in a distribution?

If it's the former, this would be relatively simple to implement. We already have a similar view in the Admin UI:

<img width="1015" alt="Screen Shot 2020-05-01 at 1 07 28 PM" src="https://user-images.githubusercontent.com/294415/80829459-c856f800-8bac-11ea-86c5-93b74f2f3fc5.png">

If it's the latter, it's going to be quite a bit more challenging, as PyPI does not actually extract any files from the distribution archives or do any introspection of them.

**Comment by uranusjr** [comment] 2020-05-01 19:07
Metadata extraction would be very useful for wheels, but for source inspection is the only way to inspect an sdist. I think both are valuable features, but this issue is more about the latter.

**Comment by di** [comment] 2020-05-19 15:36
Closing as a duplicate of #5118.

**Closed by di** 2020-05-19 15:36 UTC
Labels: feature request
